-- Outbound tracking for the cold-email engine (announced in #prova-build
-- 2026-10-07, no objection). Entirely ADDITIVE: three nullable columns and
-- two defaulted ones on SalesLead, two new tables. Every lead that exists
-- today reads doNotContact=false / outboundStatus=NEW and is otherwise
-- untouched, so the deploy that precedes this migration and the one that
-- follows it both read the table fine.
--
-- Generated by `prisma migrate diff --from-schema-datamodel <committed>
-- --to-schema-datamodel prisma/schema` — a schema-to-schema diff that
-- opens no database connection (see the --shadow-database-url entry in
-- CLAUDE.md for why that matters here).
--
-- OutboundEvent.leadId is SET NULL: a lead's delete must not be blocked by
-- its event history. ConsentRecord.leadId is RESTRICT on purpose: a consent
-- record is evidence and the lead it names cannot vanish from under it.

-- CreateEnum
CREATE TYPE "OutboundStatus" AS ENUM ('NEW', 'QUEUED', 'SEQUENCED', 'REPLIED', 'CONSENTED', 'CALLED', 'MEETING', 'DEAD');

-- AlterTable
ALTER TABLE "SalesLead" ADD COLUMN     "doNotContact" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "doNotContactAt" TIMESTAMP(3),
ADD COLUMN     "doNotContactReason" TEXT,
ADD COLUMN     "lastOutboundAt" TIMESTAMP(3),
ADD COLUMN     "outboundStatus" "OutboundStatus" NOT NULL DEFAULT 'NEW';

-- CreateTable
CREATE TABLE "OutboundEvent" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "leadId" TEXT,
    "source" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "email" TEXT,
    "vendorEventId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "occurredAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "OutboundEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ConsentRecord" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "leadId" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "textHash" TEXT NOT NULL,
    "textVersion" TEXT NOT NULL,
    "checked" BOOLEAN NOT NULL,
    "capturedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "source" TEXT,

    CONSTRAINT "ConsentRecord_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "OutboundEvent_vendorEventId_key" ON "OutboundEvent"("vendorEventId");

-- CreateIndex
CREATE INDEX "OutboundEvent_companyId_idx" ON "OutboundEvent"("companyId");

-- CreateIndex
CREATE INDEX "OutboundEvent_leadId_idx" ON "OutboundEvent"("leadId");

-- CreateIndex
CREATE INDEX "OutboundEvent_email_idx" ON "OutboundEvent"("email");

-- CreateIndex
CREATE INDEX "ConsentRecord_companyId_idx" ON "ConsentRecord"("companyId");

-- CreateIndex
CREATE INDEX "ConsentRecord_leadId_idx" ON "ConsentRecord"("leadId");

-- AddForeignKey
ALTER TABLE "OutboundEvent" ADD CONSTRAINT "OutboundEvent_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OutboundEvent" ADD CONSTRAINT "OutboundEvent_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "SalesLead"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConsentRecord" ADD CONSTRAINT "ConsentRecord_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConsentRecord" ADD CONSTRAINT "ConsentRecord_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "SalesLead"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

