import type { CoiRecord } from "./import";

/**
 * THE LIVE myCOI API ADAPTER — A STUB. IT IS NOT BUILT, AND NOTHING CALLS A
 * NETWORK FROM HERE.
 *
 * This file exists so the seam is real: the file import produces
 * `CoiRecord[]` (lib/mycoi/import.ts) and `planCoiImport` accepts them
 * regardless of where they came from, so a live source only has to produce
 * the same records. It is not wired to any page or button, and the
 * Integrations card says the live connection is unavailable in so many
 * words (see `MYCOI_LIVE_API` in lib/integrations/registry.tsx).
 *
 * WHAT WAS FOUND, 2026-09-18, so the next person does not re-run it:
 *
 *   - mycoitracking.com 301-redirects to illumend.ai. myCOI's product is now
 *     "illumend, from myCOI".
 *   - https://www.illumend.ai/integrations says "Our REST API covers the
 *     whole onboarding path" and answers "Does illumend have an API? Yes."
 *     It links NO developer documentation, no authentication guide and no
 *     way to obtain a key; its calls to action are /schedule-a-demo and
 *     /support.
 *   - https://api.illumend.ai/openapi.json is publicly reachable and is the
 *     autogenerated spec of their own application backend — titled
 *     "Customer Manager API", version 0.1.0. It declares no security scheme
 *     at all; its operations take optional `x-api-key`, `x-auth-id` and
 *     `x-business-id` headers, and an unauthenticated call answers 401. It
 *     also carries cron, backoffice and "impersonate company" routes. That
 *     is an internal surface that happens to be visible, not a published,
 *     versioned contract, and building on it would be building on
 *     something the vendor can change on any deploy without telling anyone.
 *   - apitracker.io's myCOI profile lists "Developer docs", "Sandbox",
 *     "OpenAPI" and the rest as empty placeholder categories with no links.
 *   - Procore's own myCOI integration page requires a Procore sign-in.
 *
 * So access to a live API means a customer account with illumend plus their
 * agreement to API access, arranged through their sales team. Until that
 * exists there is nothing honest to put here, and no environment variable
 * is defined for it — a variable that nothing reads is worse than none
 * (see ALLOW_PREVIEW_MIGRATIONS in CLAUDE.md).
 */

export type MyCoiLiveResult =
  | { ok: true; records: CoiRecord[] }
  | { ok: false; reason: "partner-agreement-required"; message: string };

export const MYCOI_API_UNAVAILABLE =
  "A live myCOI connection needs an API agreement with illumend (myCOI's company), which C Stream does not have yet. Import a myCOI export file instead.";

/**
 * Always refuses, without touching the network. Returns rather than throws,
 * so a caller added later renders the sentence instead of a redacted error.
 */
export async function fetchMyCoiCertificates(): Promise<MyCoiLiveResult> {
  return { ok: false, reason: "partner-agreement-required", message: MYCOI_API_UNAVAILABLE };
}
