/**
 * Every sentence the field screens say, in English, and the source the
 * Spanish is checked against key for key.
 *
 * Keys are `screen.thing`, and the value is the sentence rather than a
 * word where the sentence is what matters — "Nothing outstanding on this
 * job." carries a claim, and a key called `punch.empty` translated as a
 * noun phrase would lose it. `{placeholders}` are filled at the call.
 *
 * SCOPED TO THE FIELD SCREENS on purpose. The office half of the app is
 * read by the person who bought it; these are the screens a hanger or a
 * taper is handed.
 */
export const EN = {
  // Shared across the field screens
  "common.pendingSync": "Pending sync: {count}",
  "common.syncing": "Syncing…",
  "common.tryAgain": "Try again",
  "common.dismiss": "Dismiss",
  "common.optional": "Optional",
  "common.notSaved.one": "1 change wasn't saved",
  "common.notSaved.many": "{count} changes weren't saved",
  "common.date": "Date",
  "common.note": "Note",
  "common.required": "Required.",

  // Punch list
  "punch.status.open": "Open",
  "punch.status.ready": "Ready for review",
  "punch.status.verified": "Verified",
  "punch.markReady": "Mark as ready for review",
  "punch.markOpen": "Mark as still open",
  "punch.verifiedOnWeb": "Verified items are reopened on the web, with a reason.",
  "punch.noPhoto": "No photo of the fix — add one",
  "punch.empty.title": "Nothing outstanding on this job.",
  "punch.empty.body": "Tap “Add item” to log what still needs fixing.",
  "punch.add": "Add item",
  "punch.sheet.title": "Add punch list item",
  "punch.sheet.save": "Save item",
  "punch.field.what": "What needs fixing",
  "punch.field.whatHint": "e.g. Ceiling grid out of level",
  "punch.field.where": "Where (optional)",
  "punch.field.whereHint": "e.g. Level 3 corridor",
  "punch.due": "due {date}",

  // The outbox
  "outbox.waiting": "Waiting to send",
  "outbox.needsAttention": "Needs attention",
  "outbox.needsAttention.body": "The server read these and said no. They will not go up on their own.",
  "outbox.serverSaid": "The server said: “{error}”",
  "outbox.putBack": "Put them back on",
  "outbox.letGo": "Let them go",
  "outbox.sendNow": "Send now",
  "outbox.sending": "Sending…",
  "outbox.remove": "Remove",
  "outbox.empty.title": "Everything on this phone has reached the office.",
  "outbox.empty.body":
    "Anything you save with no signal waits here until it can go up, and this screen tells you which.",
  "outbox.stillOffline": "Still no connection. Everything here is kept until there is.",
  "outbox.signInAgain": "Sign-in expired — open any screen to sign in again, then send.",
  "outbox.waitingForSignal": "Waiting for signal",
  "outbox.tried.one": "Tried once — the server said “{error}”. Trying again {when}.",
  "outbox.tried.many": "Tried {count} times — the server said “{error}”. Trying again {when}.",
  "outbox.when.seconds": "in {seconds}s",
  "outbox.when.next": "next time there's signal",
  "outbox.triesLeft.one": "One more try, then it moves to Needs attention.",
  "outbox.triesLeft.many": "{count} more tries, then it moves to Needs attention.",

  // Time
  "time.log": "Log time",
  "time.sheet.title": "Log time",
  "time.signDay": "Sign the day",
  "time.sign.title": "Sign the day",
  "time.sign.primary": "Sign and lock",
  "time.field.hoursAll": "Hours for everyone",
  "time.field.hoursDifferent": "Hours (if different)",
  "time.field.hoursHint": "e.g. 8 or 8.5",
  "time.field.noteHint": "Optional — goes on every entry",
  "time.field.yourName": "Your name",
  "time.field.yourNameHint": "Printed under the signature",
  "time.who": "Who",
  "time.me": "Me",
  "time.craft": "Craft",
  "time.costCode": "Cost code",
  "time.noLine": "No specific line",
  "time.payType": "Pay type",
  "time.signature": "Signature",
  "time.clockIn": "Clock in",
  "time.clockOut": "Clock out",
  "time.notOnClock": "Not on the clock",
  "time.checkingClock": "Checking the clock…",
  "time.ratioWarning": "Apprentice ratio — over today",
  "time.empty.title": "No time logged",
  "time.empty.body": "Tap “Log time” to record the day's hours.",

  // Photos
  "photos.take": "Take photo",
  "photos.sheet.title": "Save photo",
  "photos.sheet.save": "Save photo",
  "photos.caption": "Caption",
  "photos.tags": "Tags",
  "photos.attachTo": "Attach to",
  "photos.onReport": "On the day's report",
  "photos.onPunchItem": "On a punch list item",
  "photos.stamped": "The time and place are burned into the photo when you save it.",
  "photos.empty.title": "No photos yet",
  "photos.empty.body":
    "Tap “Take photo”. Each one is stamped with the time and place it was taken, and goes up when there's signal.",

  // Safety
  "safety.talks": "Toolbox talks",
  "safety.incidents": "Incidents",
  "safety.addTalk": "Add talk",
  "safety.addIncident": "Add incident",
  "safety.talk.title": "Add toolbox talk",
  "safety.talk.save": "Save talk",
  "safety.incident.title": "Add incident",
  "safety.incident.save": "Save incident",
  "safety.field.topic": "Topic",
  "safety.field.topicHint": "e.g. Fall protection",
  "safety.field.employee": "Employee name",
  "safety.field.description": "Description",
  "safety.field.descriptionHint": "What happened",
  "safety.classification": "Classification",
  "safety.outcome": "Outcome",
  "safety.noTalks": "No talks logged",
  "safety.noIncidents": "No incidents",

  // The offline note, said on every field screen
  "offline.stale": "Showing what this phone last loaded, {age} — no connection",
  "offline.nothing":
    "Can't load this right now, and this phone hasn't loaded it before. Anything you add is kept and sent when you're back in range.",
  "offline.cantLoad": "Can't load {thing} right now.",
  "offline.cantLoad.body":
    "No connection, and this phone hasn't loaded this before. Anything you add is kept and sent when you're back in range.",

  // The empty states on the list screens that are NOT otherwise in the
  // field set (drawings, materials, reports, T&M, the schedule, the jobs
  // list). They share `emptyFor` and the offline note with the field
  // screens, so they share the language too — the alternative is a
  // Spanish note above an English empty state on the same screen.
  "materials.empty.title": "Nothing on order",
  "materials.empty.body": "Tap “Add order” to log a material delivery.",
  "reports.empty.title": "No reports yet",
  "reports.empty.body":
    "Tap “New report” to file the day's work. The crew and the weather fill in on their own.",
  "tickets.empty.title": "No T&M tickets",
  "tickets.empty.body": "Tap “New ticket” to document and sign the day's extra work.",
  "drawings.empty.title": "No drawing sets on this job.",
  "drawings.empty.body": "Sets and revisions are recorded on the web, off the transmittal.",
  "schedule.empty.title": "Nobody is scheduled on this job.",
  "schedule.empty.body": "Days are planned on the web, under Deployment.",
  "jobs.onThisJob": "On this job",
  "jobs.empty.title": "No jobs yet",
  "jobs.empty.body": "Jobs appear here once they're created in the office.",

  // How old a cached list is, said in words. Part of the same sentence
  // as offline.stale, so it has to speak the same language as the rest of
  // it — a Spanish note ending "2 hours ago" is the half-translated
  // screen this feature is scoped to avoid.
  "age.justNow": "just now",
  "age.minutes": "{count} min ago",
  "age.hour": "an hour ago",
  "age.hours": "{count} hours ago",
  "age.yesterday": "yesterday",
  "age.days": "{count} days ago",
  "age.earlier": "earlier",

  // What each list is called INSIDE the "can't load …" sentence, which is
  // why they carry their article: "Can't load the punch list right now."
  "thing.punchList": "the punch list",
  "thing.time": "the hours",
  "thing.photos": "the photos",
  "thing.safety.talks": "the safety talks",
  "thing.safety.incidents": "the incidents",
  "thing.materials": "the material orders",
  "thing.reports": "the field reports",
  "thing.tickets": "the T&M tickets",
  "thing.drawings": "the drawings",
  "thing.schedule": "the schedule",
  "thing.jobs": "the job list",

  // The navigation bar. Short on purpose — these sit in an iOS header,
  // which truncates rather than wraps, so a title that reads well in a
  // sentence does not belong here. The longer name lives in `thing.*`.
  "nav.home": "Home",
  "nav.jobs": "Jobs",
  "nav.back": "Back",
  "nav.job": "Job",
  "nav.reports": "Field reports",
  "nav.photos": "Photos",
  "nav.safety": "Safety",
  "nav.time": "Time",
  "nav.materials": "Materials",
  "nav.punch": "Punch list",
  "nav.ticket": "T&M ticket",
  "nav.drawings": "Drawings",
  "nav.schedule": "Schedule",
  "nav.outbox": "Waiting to send",

  // The More tab. In scope for a reason that is almost circular: it is
  // where the language switch lives, and making somebody read an English
  // screen to find "Idioma" is the whole problem in miniature.
  "settings.title": "More",
  "settings.account": "Account",
  "settings.account.owner": "Account owner — everything on this phone is yours to see",
  "settings.account.role":
    "{role} — the account owner sets what that includes, on the Team page",
  "settings.account.full": "Full access to this company's records",
  "settings.outbox.clear": "Everything has reached the office",
  "settings.outbox.waiting": "{count} waiting",
  "settings.outbox.attention": "{count} need attention",
  "settings.reminder": "Unsent work reminder",
  "settings.reminder.label": "Remind me about unsent work",
  "settings.reminder.off": "Off",
  "settings.reminder.blocked":
    "Notifications are off for Prova in iOS Settings, so this cannot show. Everything still waits safely on the phone.",
  "settings.reminder.note":
    "Only if something is still unsent at that time. Nothing is sent to anyone else.",
  "settings.job": "Job",
  "settings.leave": "Leave {job}",
  "settings.signOut": "Sign out",

  // Language, in Settings
  // DELIBERATELY NO `settings.language.en` / `.es`. A language is named in
  // its own language — "English" stays English in a Spanish app and
  // "Español" stays Español in an English one — so those two names are
  // literals in the switch, not keys. They were keys once, nothing
  // referenced them, and the census caught it.
  "settings.language": "Language",
  "settings.language.auto": "Follow the phone",
  "settings.language.note":
    "Changes this phone only. The office keeps everything in English either way.",

  // photos-handover
  "photos.library": "Library",
  "photos.locationOff": "Location is off for C Stream, so this photo has no place on it.",
  "photos.locationFailed": "Couldn't get a location fix, so this photo has no place on it.",
  "photos.cameraOff": "The camera is off for C Stream. Turn it on in Settings to take site photos.",
  "photos.busy.location": "Reading location…",
  "photos.busy.stamping": "Stamping…",
  "photos.stampFailed": "The stamp could not be drawn. Try the photo again.",
  "photos.saveFailed": "Could not save that photo",
  "photos.noLocation": "No location recorded",
  "photos.todaysReport": "Today's report",
  "photos.noReportToday": "No report today",
  "handover.intro": "Put your own hours in. Only you and this job are on this screen — nothing else on the phone is open while you have it.",
  "handover.field.hours": "Hours worked today",
  "handover.field.note": "Anything worth noting (optional)",
  "handover.field.noteHint": "Hung rock, level 3",
  "handover.add": "Add these hours",
  "handover.saved.title": "On this phone, waiting to send",
  "handover.saved.row": "{hours} hours · {name}",
  "handover.saved.note": "Kept on the phone and sent when there is signal. Nothing is lost if there is none.",
  "handover.signFinish": "Sign and finish",
  "handover.sign.title": "{name} — sign for today",
  "handover.sign.note": "Signing says these are your hours for {date} on {job}. It goes to the office with them.",
  "handover.handBack": "Hand the phone back",
  "handover.handBack.primary": "Hand it back",
  "handover.back.pinNote": "The foreman set a PIN when they handed it over. Give the phone back to them to type it.",
  "handover.back.note": "This ends your turn on the phone. Anything you have put in is kept and sent either way.",
  "handover.pin.label": "Foreman's PIN",
  "handover.pin.wrong": "That is not the PIN this phone was handed over with.",

  // reports
  "reports.new": "New report",
  "reports.sheet.title": "New daily report",
  "reports.sheet.save": "File report",
  "reports.sheet.hint": "The crew comes from the day's logged hours and the weather from the job's site address. Log delays separately so each has a cause and crew-hours.",
  "reports.problem.daySigned": "{date} is signed, so its report is locked.",
  "reports.problem.exists": "There's already a report for {date}. Edit it on the web.",
  "reports.problem.delaysLocked": "{date} is signed, so its delays are locked.",
  "reports.locked.approved": "Approved · locked",
  "reports.locked.signed": "Signed · locked",
  "reports.crew": "Crew: {crew}",
  "reports.alsoOnSite": "Also on site: {who}",
  "reports.weather": "Weather: {weather}",
  "reports.weatherForecast": "Weather (forecast): {weather}",
  "reports.siteConditions": "Site conditions: {conditions}",
  "reports.delays": "Delays: {delays}",
  "reports.noReportForDay": "No report filed for this day.",
  "reports.delay.log": "Log a delay",
  "reports.delay.sheetTitle": "Log a delay",
  "reports.delay.save": "Save delay",
  "reports.delay.headline": "Delay · {cause} · {party}",
  "reports.delay.crewHours": "{count} crew-hours",
  "reports.delay.gcTold": "GC told by {how}",
  "reports.delay.gcNotTold": "GC not told yet",
  "reports.field.work": "Work performed",
  "reports.field.workHint": "What got done",
  "reports.field.others": "Other trades / visitors on site",
  "reports.field.othersHint": "Optional — e.g. electricians on L3, inspector at 10",
  "reports.field.conditions": "Site conditions",
  "reports.field.conditionsHint": "Optional — the weather fills in on its own",
  "reports.field.cause": "Cause",
  "reports.field.causedBy": "Caused by",
  "reports.field.who": "Who, by name",
  "reports.field.whoHint": "Optional — e.g. Acme Electric",
  "reports.field.what": "What happened",
  "reports.field.whatHint": "What stopped the work",
  "reports.field.from": "From",
  "reports.field.to": "To",
  "reports.field.workers": "Workers affected",
  "reports.field.hoursLost": "Crew-hours lost",
  "reports.field.hoursLostHint": "Worked out",
  "reports.field.gcTold": "GC told?",
  "reports.gcTold.notYet": "Not yet",
  "reports.field.toldWho": "Told who",
  "reports.field.toldWhoHint": "e.g. Sam, the super",
  "reports.cause.weather": "Weather",
  "reports.cause.gcSchedule": "GC schedule",
  "reports.cause.otherTrade": "Other trade",
  "reports.cause.material": "Material",
  "reports.cause.inspection": "Inspection",
  "reports.cause.designRfi": "Design / RFI",
  "reports.cause.siteAccess": "Site access",
  "reports.cause.equipment": "Equipment",
  "reports.cause.other": "Other",
  "reports.party.gc": "GC",
  "reports.party.owner": "Owner",
  "reports.party.otherTrade": "Another trade",
  "reports.party.supplier": "Supplier",
  "reports.party.us": "Us",
  "reports.party.nobody": "Nobody",
  "reports.method.phone": "Phone",
  "reports.method.email": "Email",
  "reports.method.text": "Text",
  "reports.method.inPerson": "In person",
  "reports.method.meeting": "Meeting",

  // ticket-materials
  "tickets.signed": "Signed: {name}",
  "tickets.typed": "(typed)",
  "tickets.snapshot.labor.one": "1 labour entry",
  "tickets.snapshot.labor.many": "{count} labour entries",
  "tickets.snapshot.materials.one": "1 material",
  "tickets.snapshot.materials.many": "{count} materials",
  "tickets.new": "New ticket",
  "tickets.sheet.title": "New T&M ticket",
  "tickets.sheet.save": "Sign & save",
  "tickets.field.what": "What was done",
  "tickets.field.whatHint": "Describe the extra work",
  "tickets.field.signer": "Client's name",
  "tickets.field.signerHint": "Printed under their signature",
  "tickets.field.signature": "Client's signature",
  "materials.ordered": "Ordered {date}",
  "materials.due": "due {date}",
  "materials.add": "Add order",
  "materials.sheet.title": "Add material order",
  "materials.sheet.save": "Save order",
  "materials.field.what": "What was ordered",
  "materials.field.whatHint": "e.g. 2x4 lumber",
  "materials.field.orderedOn": "Date ordered",
  "materials.field.promisedFor": "Promised for",
  "materials.field.vendor": "Vendor",

  // time
  "time.ratio.scheduledCrew": "Scheduled crew",
  "time.ratio.hoursLogged": "Hours logged",
  "time.ratio.apprentices.one": "1 apprentice",
  "time.ratio.apprentices.many": "{count} apprentices",
  "time.ratio.journeymen.one": "1 journeyman",
  "time.ratio.journeymen.many": "{count} journeymen",
  "time.ratio.apprenticeHours": "{hours}h apprentice",
  "time.ratio.journeymanHours": "{hours}h journeyman",
  "time.ratio.noJourneyman": "{where}: {apprentices} and no journeyman {rule}.",
  "time.ratio.line": "{where}: {apprentices} to {journeymen}{allowed} {rule}.",
  "time.ratio.allowed": "{allowed} allowed",
  "time.craft.noneSetUp": "No crafts are set up for this company, so these hours will show as untagged on certified payroll.",
  "time.craft.noneTicked": "No crafts are ticked for {who} yet, so every craft is shown. Tick them on the web under Union compliance.",
  "time.you": "you",
  "time.crewMember": "Crew member",
  "time.clock.onTheClock": "On the clock · {elapsed}",
  "time.clock.clockedInOn": "Clocked in on {job}",
  "time.clock.anotherJob": "another job",
  "time.clock.break": "Break: {minutes} min",
  "time.clock.minBreak": "{minutes} min break",
  "time.clock.switch": "Switch",
  "time.clock.switchToThisJob": "Switch to this job",
  "time.clock.start": "Start",
  "time.clock.alreadyOn": "You're already on the clock. Clock out or switch instead.",
  "time.clock.nothingToRecord": "Nothing to record: the {minutes}-minute break is as long as the time on the clock. Lower the break first.",
  "time.day.today": "Today",
  "time.day.earlier": "Earlier",
  "time.locked.approved": "Approved · locked",
  "time.locked.signed": "Signed · locked",
  "time.dayLocked.signed": "{date} is signed, so its hours are locked. The office can reopen it on the web.",
  "time.dayLocked.approved": "{date} is signed and approved, so its hours are locked. The office can reopen it on the web.",
  "time.save.one": "Save entry",
  "time.save.many": "Save {count} entries",
  "time.hoursRange": "Hours must be more than 0 and at most 24.",
  "time.pickCraft": "Pick a craft.",
  "time.noCostCodes": "This job has no cost codes yet, so these hours go on no specific line.",
  "time.copyCrew": "Copy crew from {date}",
  "time.field.sameAsEveryone": "{hours} — same as everyone",
  "time.handover.button": "Hand phone over",
  "time.handover.title": "Hand the phone over",
  "time.handover.primary": "Hand it over",
  "time.handover.note": "They will see one screen — their own hours for today on this job, and a place to sign. Nothing else on the phone is open while they have it.",
  "time.handover.noCrew": "No crew members on this company yet. They are added on the web, under Team.",
  "time.handover.pin": "PIN to get the phone back (optional)",
  "time.handover.pinHint": "4 digits",
  "time.handover.pinNote": "Without a PIN, anyone holding the phone can hand it back — which is usually fine, because you are standing there. With one, it does not come back until you type it.",
  "time.alreadySignedBy": "{date} is already signed by {name}.",
  "time.noHoursToSign": "No hours on {date} to sign.",
  "time.thatDay": "that day",
  "time.entries.one": "1 entry · {hours}h",
  "time.entries.many": "{count} entries · {hours}h",
  "time.report.filed": "Daily report: filed",
  "time.report.notFiled": "Daily report: not filed yet",
  "time.delays.one": "1 delay",
  "time.delays.many": "{count} delays",
  "time.signing.locks": "Signing locks these hours. Anything still waiting to sync goes up first. If something is wrong later, the office reopens the day on the web.",
  "time.signing.locksWithReport": "Signing locks these hours, the daily report and its delays. Anything still waiting to sync goes up first. If something is wrong later, the office reopens the day on the web.",

  // drawings-schedule
  "drawings.notOnSite": "Current revision hasn't reached site — the crew is on {label}",
  "drawings.nothingYet": "nothing yet",
  "drawings.current": "current",
  "drawings.onThisPhone": "On this phone",
  "drawings.issued": "Issued {date}",
  "drawings.received": "received {date}",
  "drawings.notReceived": "not received",
  "drawings.open": "Open",
  "drawings.saving": "Saving…",
  "drawings.removeFromPhone": "Remove from phone",
  "drawings.keepOnPhone": "Keep on phone",
  "drawings.noFile": "No file recorded for this revision",
  "drawings.kept": "{size} of drawings kept on this phone",
  "drawings.cantOpen": "Couldn't open that drawing.",
  "drawings.cantOpenSaved": "This build can't open a saved drawing yet — it opens online until the app is rebuilt.",
  "drawings.cantDownload": "Couldn't download that drawing — try again in range.",
  "schedule.today": "Today",
  "schedule.past": "past",
  "schedule.noHours": "No hours logged",

  // home-today
  "home.greeting.morning": "Good morning",
  "home.greeting.afternoon": "Good afternoon",
  "home.greeting.evening": "Good evening",
  "home.today": "Today",
  "common.loading": "Loading…",
  "home.empty.notYours.title": "Today isn't your screen",
  "home.empty.notYours.body": "Home is the day on a job — reports, photos, the punch list, hours — and field records aren't part of your job function. The jobs themselves are still on the Jobs tab.",
  "home.empty.noJob.title": "Pick a job to start the day",
  "home.empty.noJob.body": "Once you're on a job, this page shows what's done and what isn't — and the capture button works without asking which job every time.",
  "home.offline.nothing": "No connection, and this phone hasn't loaded this job yet",
  "home.photos.all": "All of today's photos",
  "home.photos.open": "Open photos",
  "today.pending.one": "1 change still to send",
  "today.pending.many": "{count} changes still to send",
  "today.report.filed": "Today's report is filed",
  "today.report.notFiled": "Today's report isn't filed",
  "today.time.none": "No hours logged today",
  "today.time.hour.onePerson": "{hours} hour logged today, 1 person",
  "today.time.hour.manyPeople": "{hours} hour logged today, {people} people",
  "today.time.hours.onePerson": "{hours} hours logged today, 1 person",
  "today.time.hours.manyPeople": "{hours} hours logged today, {people} people",
  "today.punch.open.one": "1 punch item open",
  "today.punch.open.many": "{open} punch items open",
  "today.punch.waiting": "{waiting} waiting to be verified",
  "today.punch.openAndWaiting.one": "1 punch item open, {waiting} waiting to be verified",
  "today.punch.openAndWaiting.many": "{open} punch items open, {waiting} waiting to be verified",
  "today.punch.clear": "Punch list is clear",
  "today.photos.none": "No photos today",
  "today.photos.one": "1 photo today",
  "today.photos.many": "{count} photos today",

  // shared
  "outbox.noReason": "no reason given",
  "outbox.op.thisJob": "this job",
  "outbox.op.dailyReport": "Daily report",
  "outbox.op.dailyReportChange": "Change to a daily report",
  "outbox.op.hours": "{hours} hours",
  "outbox.op.materialOrder": "Material order · {job}",
  "outbox.op.toolboxTalk": "Toolbox talk · {job} · {date}",
  "outbox.op.incident": "Incident · {name}",
  "outbox.op.punchItem": "Punch item · {job}",
  "outbox.op.punchReady": "Punch item marked ready",
  "outbox.op.punchReopened": "Punch item reopened",
  "outbox.op.tmTicket": "T&M ticket · {job} · {date}",
  "outbox.op.photo": "Photo",
  "outbox.op.delay": "Delay",
  "outbox.op.signoff": "Timesheet signed by {name}",
  "common.throwAway": "Throw away",
  "common.notSavedItems.one": "1 item wasn't saved",
  "common.notSavedItems.many": "{count} items weren't saved",
  "job.chip.on": "On this job",
  "job.chip.none": "No job picked",
  "job.chip.choose": "Choose one to get started",
  "job.chip.pick": "Pick",
  "job.chip.a11y": "On {job}. Tap to switch job.",
  "job.chip.a11yNone": "Pick a job",
  "date.yesterday": "Yesterday",
  "date.otherDay": "Other day…",
  "date.previousMonth": "Previous month",
  "date.nextMonth": "Next month",
  "signature.here": "Sign here",
  "signature.clear": "Clear",
  "notYourJob.title": "{what} aren't part of your job function.",
  "notYourJob.body": "The account owner sets who sees what, on the Team page. Nothing is missing from this phone — it is not yours to see.",
  "notYourJob.noun.reports": "Field reports",
  "notYourJob.noun.photos": "Site photos",
  "notYourJob.noun.punch": "Punch lists",
  "notYourJob.noun.time": "Time records",
  "notYourJob.noun.materials": "Material orders",
  "notYourJob.noun.safety": "Safety records",
  "notYourJob.noun.tickets": "T&M tickets",
  "notYourJob.noun.schedule": "The crew schedule",
  "notYourJob.noun.drawings": "Drawings",

  // capture
  "capture.title": "Capture",
  "capture.pickFirst": "Pick a job first — everything here gets filed against one, and guessing which is how a photo ends up on the wrong site.",
  "capture.pickJob": "Pick a job",
  "capture.photo": "Photo",
  "capture.photo.sub": "Stamped with time and place",
  "capture.report": "Field report",
  "capture.report.sub": "What got done today",
  "capture.time": "Time",
  "capture.time.sub": "Hours for the crew",
  "capture.punch": "Punch item",
  "capture.punch.sub": "Something that needs fixing",
  "capture.safety": "Safety",
  "capture.safety.sub": "Toolbox talk or an incident",
  "capture.materials": "Material order",
  "capture.materials.sub": "What to get on site",
  "capture.ticket": "T&M ticket",
  "capture.ticket.sub": "Signed time and materials",
} as const;
