import type { EN } from "./en";

/**
 * The field screens in Spanish — Mexican usage, because that is who is
 * on these crews in the Southwest.
 *
 * WORDS WORTH A NATIVE SPEAKER'S EYE, flagged rather than buried. A
 * foreman correcting any of them is a one-line change to this file:
 *
 *   punch list      "lista de pendientes". Also heard as "lista de
 *                   detalles" on Mexican jobs; "detalle" for one item is
 *                   common and is what I would change to if your crews
 *                   use it.
 *   job / site      "obra", not "trabajo" — "trabajo" is the work, "obra"
 *                   is the place with an address.
 *   toolbox talk    "plática de seguridad". "Charla" is the Spain usage;
 *                   "plática" is Mexico.
 *   cost code       "código de costo", left close to the English because
 *                   the codes themselves are English on the paperwork.
 *   T&M             left as "T&M" wherever it appears — it is what the GC
 *                   writes on the ticket, and translating it would make
 *                   the phone disagree with the paper.
 *   the server      "el sistema". Nobody outside this building calls it a
 *                   server, and "el servidor" reads as a machine somebody
 *                   should go and find.
 *
 * Safety and incident wording is deliberately plain and short: this is
 * the one place where a clever translation could change what somebody
 * believes they are reporting.
 */
export const ES: Record<keyof typeof EN, string> = {
  "common.pendingSync": "Pendientes por enviar: {count}",
  "common.syncing": "Enviando…",
  "common.tryAgain": "Reintentar",
  "common.dismiss": "Descartar",
  "common.optional": "Opcional",
  "common.notSaved.one": "1 cambio no se guardó",
  "common.notSaved.many": "{count} cambios no se guardaron",
  "common.date": "Fecha",
  "common.note": "Nota",
  "common.required": "Obligatorio.",

  "punch.status.open": "Abierto",
  "punch.status.ready": "Listo para revisión",
  "punch.status.verified": "Verificado",
  "punch.markReady": "Marcar como listo para revisión",
  "punch.markOpen": "Marcar como abierto otra vez",
  "punch.verifiedOnWeb": "Los pendientes verificados se reabren en la computadora, con un motivo.",
  "punch.noPhoto": "Sin foto del arreglo — agrega una",
  "punch.empty.title": "No hay pendientes en esta obra.",
  "punch.empty.body": "Toca «Agregar pendiente» para anotar lo que falta arreglar.",
  "punch.add": "Agregar pendiente",
  "punch.sheet.title": "Agregar pendiente",
  "punch.sheet.save": "Guardar",
  "punch.field.what": "Qué hay que arreglar",
  "punch.field.whatHint": "ej. Plafón fuera de nivel",
  "punch.field.where": "Dónde (opcional)",
  "punch.field.whereHint": "ej. Pasillo del nivel 3",
  "punch.due": "para el {date}",

  "outbox.waiting": "Por enviar",
  "outbox.needsAttention": "Necesita atención",
  "outbox.needsAttention.body": "El sistema los leyó y los rechazó. No se van a enviar solos.",
  "outbox.serverSaid": "El sistema dijo: «{error}»",
  "outbox.putBack": "Volver a intentarlos",
  "outbox.letGo": "Descartarlos",
  "outbox.sendNow": "Enviar ahora",
  "outbox.sending": "Enviando…",
  "outbox.remove": "Quitar",
  "outbox.empty.title": "Todo lo de este teléfono ya llegó a la oficina.",
  "outbox.empty.body":
    "Lo que guardes sin señal espera aquí hasta que se pueda enviar, y esta pantalla te dice qué es.",
  "outbox.stillOffline": "Sigue sin conexión. Todo esto se guarda hasta que haya.",
  "outbox.signInAgain": "La sesión expiró — abre cualquier pantalla para entrar otra vez, y luego envía.",
  "outbox.waitingForSignal": "Esperando señal",
  "outbox.tried.one": "Se intentó una vez — el sistema dijo «{error}». Se vuelve a intentar {when}.",
  "outbox.tried.many": "Se intentó {count} veces — el sistema dijo «{error}». Se vuelve a intentar {when}.",
  "outbox.when.seconds": "en {seconds}s",
  "outbox.when.next": "cuando haya señal",
  "outbox.triesLeft.one": "Un intento más y pasa a Necesita atención.",
  "outbox.triesLeft.many": "{count} intentos más y pasa a Necesita atención.",

  "time.log": "Registrar horas",
  "time.sheet.title": "Registrar horas",
  "time.signDay": "Firmar el día",
  "time.sign.title": "Firmar el día",
  "time.sign.primary": "Firmar y cerrar",
  "time.field.hoursAll": "Horas para todos",
  "time.field.hoursDifferent": "Horas (si son distintas)",
  "time.field.hoursHint": "ej. 8 u 8.5",
  "time.field.noteHint": "Opcional — se aplica a todos los registros",
  "time.field.yourName": "Tu nombre",
  "time.field.yourNameHint": "Se imprime debajo de la firma",
  "time.who": "Quién",
  "time.me": "Yo",
  "time.craft": "Oficio",
  "time.costCode": "Código de costo",
  "time.noLine": "Sin partida específica",
  "time.payType": "Tipo de pago",
  "time.signature": "Firma",
  "time.clockIn": "Marcar entrada",
  "time.clockOut": "Marcar salida",
  "time.notOnClock": "Sin turno iniciado",
  "time.checkingClock": "Revisando el turno…",
  "time.ratioWarning": "Proporción de aprendices — excedida hoy",
  "time.empty.title": "Sin horas registradas",
  "time.empty.body": "Toca «Registrar horas» para anotar las horas del día.",

  "photos.take": "Tomar foto",
  "photos.sheet.title": "Guardar foto",
  "photos.sheet.save": "Guardar foto",
  "photos.caption": "Descripción",
  "photos.tags": "Etiquetas",
  "photos.attachTo": "Adjuntar a",
  "photos.onReport": "Al reporte del día",
  "photos.onPunchItem": "A un pendiente",
  "photos.stamped": "La hora y el lugar quedan marcados en la foto al guardarla.",
  "photos.empty.title": "Todavía no hay fotos",
  "photos.empty.body":
    "Toca «Tomar foto». Cada una queda marcada con la hora y el lugar, y se envía cuando haya señal.",

  "safety.talks": "Pláticas de seguridad",
  "safety.incidents": "Incidentes",
  "safety.addTalk": "Agregar plática",
  "safety.addIncident": "Agregar incidente",
  "safety.talk.title": "Agregar plática de seguridad",
  "safety.talk.save": "Guardar plática",
  "safety.incident.title": "Agregar incidente",
  "safety.incident.save": "Guardar incidente",
  "safety.field.topic": "Tema",
  "safety.field.topicHint": "ej. Protección contra caídas",
  "safety.field.employee": "Nombre del trabajador",
  "safety.field.description": "Descripción",
  "safety.field.descriptionHint": "Qué pasó",
  "safety.classification": "Clasificación",
  "safety.outcome": "Resultado",
  "safety.noTalks": "Sin pláticas registradas",
  "safety.noIncidents": "Sin incidentes",

  "offline.stale": "Mostrando lo último que cargó este teléfono, {age} — sin conexión",
  "offline.nothing":
    "No se puede cargar ahora, y este teléfono no lo ha cargado antes. Lo que agregues se guarda y se envía cuando vuelvas a tener señal.",
  "offline.cantLoad": "No se puede cargar {thing} ahora.",
  "offline.cantLoad.body":
    "Sin conexión, y este teléfono no lo ha cargado antes. Lo que agregues se guarda y se envía cuando vuelvas a tener señal.",

  "materials.empty.title": "Sin pedidos",
  "materials.empty.body": "Toca «Agregar pedido» para anotar una entrega de material.",
  "reports.empty.title": "Todavía no hay reportes",
  "reports.empty.body":
    "Toca «Nuevo reporte» para registrar el trabajo del día. La cuadrilla y el clima se llenan solos.",
  "tickets.empty.title": "Sin tickets de T&M",
  "tickets.empty.body": "Toca «Nuevo ticket» para documentar y firmar el trabajo extra del día.",
  "drawings.empty.title": "No hay juegos de planos en esta obra.",
  "drawings.empty.body": "Los juegos y sus revisiones se registran en la computadora, desde el transmittal.",
  "schedule.empty.title": "Nadie está programado en esta obra.",
  "schedule.empty.body": "Los días se programan en la computadora, en Deployment.",
  "jobs.onThisJob": "En esta obra",
  "jobs.empty.title": "Todavía no hay obras",
  "jobs.empty.body": "Las obras aparecen aquí cuando se crean en la oficina.",

  "age.justNow": "hace un momento",
  "age.minutes": "hace {count} min",
  "age.hour": "hace una hora",
  "age.hours": "hace {count} horas",
  "age.yesterday": "ayer",
  "age.days": "hace {count} días",
  "age.earlier": "antes",

  "thing.punchList": "la lista de pendientes",
  "thing.time": "las horas",
  "thing.photos": "las fotos",
  "thing.safety.talks": "las pláticas de seguridad",
  "thing.safety.incidents": "los incidentes",
  "thing.materials": "los pedidos de material",
  "thing.reports": "los reportes diarios",
  "thing.tickets": "los tickets de T&M",
  "thing.drawings": "los planos",
  "thing.schedule": "el programa de trabajo",
  "thing.jobs": "la lista de obras",

  // The navigation bar. An iOS header truncates rather than wraps, and
  // Spanish runs longer than English — so these are the SHORT forms, not
  // the `thing.*` phrases. "Pendientes" over "Lista de pendientes" for
  // that reason alone; the full name is on the screen underneath.
  "nav.home": "Inicio",
  "nav.jobs": "Obras",
  "nav.back": "Atrás",
  "nav.job": "Obra",
  "nav.reports": "Reportes diarios",
  "nav.photos": "Fotos",
  "nav.safety": "Seguridad",
  "nav.time": "Horas",
  "nav.materials": "Materiales",
  "nav.punch": "Pendientes",
  "nav.ticket": "Ticket T&M",
  "nav.drawings": "Planos",
  "nav.schedule": "Programa",
  "nav.outbox": "Por enviar",

  // The More tab. `{role}` arrives from the API already in English
  // (OWNER, FOREMAN…) and is left that way on purpose — it is what the
  // office set on the Team page, and translating it here would name a
  // role nobody can find in the web app.
  "settings.title": "Más",
  "settings.account": "Cuenta",
  "settings.account.owner": "Dueño de la cuenta — todo en este teléfono es suyo para ver",
  "settings.account.role":
    "{role} — el dueño de la cuenta define qué incluye eso, en la página de Equipo",
  "settings.account.full": "Acceso completo a los registros de esta compañía",
  "settings.outbox.clear": "Todo ha llegado a la oficina",
  "settings.outbox.waiting": "{count} en espera",
  "settings.outbox.attention": "{count} necesitan atención",
  "settings.reminder": "Aviso de trabajo sin enviar",
  "settings.reminder.label": "Avísame del trabajo sin enviar",
  "settings.reminder.off": "Apagado",
  "settings.reminder.blocked":
    "Las notificaciones de Prova están apagadas en Ajustes de iOS, así que esto no puede aparecer. Todo sigue guardado en el teléfono.",
  "settings.reminder.note":
    "Solo si algo sigue sin enviarse a esa hora. No se le manda nada a nadie más.",
  "settings.job": "Obra",
  "settings.leave": "Salir de {job}",
  "settings.signOut": "Cerrar sesión",

  // See en.ts: the two language NAMES are deliberately not keys.
  "settings.language": "Idioma",
  "settings.language.auto": "Seguir el teléfono",
  "settings.language.note":
    "Cambia solo este teléfono. La oficina lo ve todo en inglés de cualquier forma.",

  // photos-handover
  "photos.library": "Galería",
  "photos.locationOff": "La ubicación está apagada para C Stream, así que esta foto no lleva el lugar.",
  "photos.locationFailed": "No se pudo obtener la ubicación, así que esta foto no lleva el lugar.",
  "photos.cameraOff": "La cámara está apagada para C Stream. Actívala en Ajustes para tomar fotos de la obra.",
  "photos.busy.location": "Leyendo la ubicación…",
  "photos.busy.stamping": "Marcando la foto…",
  "photos.stampFailed": "No se pudo dibujar la marca. Toma la foto otra vez.",
  "photos.saveFailed": "No se pudo guardar esa foto",
  "photos.noLocation": "Sin ubicación registrada",
  "photos.todaysReport": "Reporte de hoy",
  "photos.noReportToday": "Hoy no hay reporte",
  "handover.intro": "Registra tus propias horas. En esta pantalla solo están tú y esta obra — nada más del teléfono está abierto mientras lo tienes.",
  "handover.field.hours": "Horas trabajadas hoy",
  "handover.field.note": "Algo que quieras anotar (opcional)",
  "handover.field.noteHint": "Colgué tablaroca, nivel 3",
  "handover.add": "Agregar estas horas",
  "handover.saved.title": "En este teléfono, por enviar",
  "handover.saved.row": "{hours} horas · {name}",
  "handover.saved.note": "Se guarda en el teléfono y se envía cuando haya señal. No se pierde nada si no la hay.",
  "handover.signFinish": "Firmar y terminar",
  "handover.sign.title": "{name} — firma por el día de hoy",
  "handover.sign.note": "Al firmar dices que estas son tus horas del {date} en {job}. La firma va a la oficina junto con ellas.",
  "handover.handBack": "Devolver el teléfono",
  "handover.handBack.primary": "Devolverlo",
  "handover.back.pinNote": "El mayordomo puso un PIN cuando te dio el teléfono. Devuélveselo para que lo escriba.",
  "handover.back.note": "Esto termina tu turno en el teléfono. Lo que hayas anotado se guarda y se envía de todas formas.",
  "handover.pin.label": "PIN del mayordomo",
  "handover.pin.wrong": "Ese no es el PIN con el que se entregó este teléfono.",

  // reports
  "reports.new": "Nuevo reporte",
  "reports.sheet.title": "Nuevo reporte diario",
  "reports.sheet.save": "Guardar reporte",
  "reports.sheet.hint": "La cuadrilla sale de las horas registradas del día y el clima de la dirección de la obra. Registra los retrasos aparte para que cada uno tenga su causa y sus horas de cuadrilla.",
  "reports.problem.daySigned": "El {date} está firmado, así que su reporte está cerrado.",
  "reports.problem.exists": "Ya hay un reporte del {date}. Edítalo en la computadora.",
  "reports.problem.delaysLocked": "El {date} está firmado, así que sus retrasos están cerrados.",
  "reports.locked.approved": "Aprobado · cerrado",
  "reports.locked.signed": "Firmado · cerrado",
  "reports.crew": "Cuadrilla: {crew}",
  "reports.alsoOnSite": "También en la obra: {who}",
  "reports.weather": "Clima: {weather}",
  "reports.weatherForecast": "Clima (pronóstico): {weather}",
  "reports.siteConditions": "Condiciones de la obra: {conditions}",
  "reports.delays": "Retrasos: {delays}",
  "reports.noReportForDay": "No se registró reporte de este día.",
  "reports.delay.log": "Registrar un retraso",
  "reports.delay.sheetTitle": "Registrar un retraso",
  "reports.delay.save": "Guardar retraso",
  "reports.delay.headline": "Retraso · {cause} · {party}",
  "reports.delay.crewHours": "{count} horas de cuadrilla",
  "reports.delay.gcTold": "Se le avisó al GC por {how}",
  "reports.delay.gcNotTold": "Todavía no se le avisó al GC",
  "reports.field.work": "Trabajo realizado",
  "reports.field.workHint": "Qué se hizo",
  "reports.field.others": "Otros oficios o visitas en la obra",
  "reports.field.othersHint": "Opcional — ej. electricistas en el nivel 3, inspector a las 10",
  "reports.field.conditions": "Condiciones de la obra",
  "reports.field.conditionsHint": "Opcional — el clima se llena solo",
  "reports.field.cause": "Causa",
  "reports.field.causedBy": "Causado por",
  "reports.field.who": "Quién, por nombre",
  "reports.field.whoHint": "Opcional — ej. Acme Electric",
  "reports.field.what": "Qué pasó",
  "reports.field.whatHint": "Qué detuvo el trabajo",
  "reports.field.from": "Desde",
  "reports.field.to": "Hasta",
  "reports.field.workers": "Trabajadores afectados",
  "reports.field.hoursLost": "Horas de cuadrilla perdidas",
  "reports.field.hoursLostHint": "Se calcula solo",
  "reports.field.gcTold": "¿Se le avisó al GC?",
  "reports.gcTold.notYet": "Todavía no",
  "reports.field.toldWho": "A quién se le avisó",
  "reports.field.toldWhoHint": "ej. Sam, el súper",
  "reports.cause.weather": "Clima",
  "reports.cause.gcSchedule": "Programa del GC",
  "reports.cause.otherTrade": "Otro oficio",
  "reports.cause.material": "Material",
  "reports.cause.inspection": "Inspección",
  "reports.cause.designRfi": "Diseño / RFI",
  "reports.cause.siteAccess": "Acceso a la obra",
  "reports.cause.equipment": "Equipo",
  "reports.cause.other": "Otro",
  "reports.party.gc": "GC",
  "reports.party.owner": "Dueño",
  "reports.party.otherTrade": "Otro oficio",
  "reports.party.supplier": "Proveedor",
  "reports.party.us": "Nosotros",
  "reports.party.nobody": "Nadie",
  "reports.method.phone": "Teléfono",
  "reports.method.email": "Correo",
  "reports.method.text": "Mensaje",
  "reports.method.inPerson": "En persona",
  "reports.method.meeting": "Junta",

  // ticket-materials
  "tickets.signed": "Firmó: {name}",
  "tickets.typed": "(nombre escrito)",
  "tickets.snapshot.labor.one": "1 registro de mano de obra",
  "tickets.snapshot.labor.many": "{count} registros de mano de obra",
  "tickets.snapshot.materials.one": "1 material",
  "tickets.snapshot.materials.many": "{count} materiales",
  "tickets.new": "Nuevo ticket",
  "tickets.sheet.title": "Nuevo ticket de T&M",
  "tickets.sheet.save": "Firmar y guardar",
  "tickets.field.what": "Qué se hizo",
  "tickets.field.whatHint": "Describe el trabajo extra",
  "tickets.field.signer": "Nombre del cliente",
  "tickets.field.signerHint": "Se imprime debajo de su firma",
  "tickets.field.signature": "Firma del cliente",
  "materials.ordered": "Pedido el {date}",
  "materials.due": "para el {date}",
  "materials.add": "Agregar pedido",
  "materials.sheet.title": "Agregar pedido de material",
  "materials.sheet.save": "Guardar pedido",
  "materials.field.what": "Qué se pidió",
  "materials.field.whatHint": "ej. Madera 2x4",
  "materials.field.orderedOn": "Fecha del pedido",
  "materials.field.promisedFor": "Prometido para",
  "materials.field.vendor": "Proveedor",

  // time
  "time.ratio.scheduledCrew": "Cuadrilla programada",
  "time.ratio.hoursLogged": "Horas registradas",
  "time.ratio.apprentices.one": "1 aprendiz",
  "time.ratio.apprentices.many": "{count} aprendices",
  "time.ratio.journeymen.one": "1 oficial",
  "time.ratio.journeymen.many": "{count} oficiales",
  "time.ratio.apprenticeHours": "{hours}h de aprendiz",
  "time.ratio.journeymanHours": "{hours}h de oficial",
  "time.ratio.noJourneyman": "{where}: {apprentices} y ningún oficial {rule}.",
  "time.ratio.line": "{where}: {apprentices} por {journeymen}{allowed} {rule}.",
  "time.ratio.allowed": "se permiten {allowed}",
  "time.craft.noneSetUp": "No hay oficios configurados para esta compañía, así que estas horas van a salir sin oficio en la nómina certificada.",
  "time.craft.noneTicked": "Todavía no hay oficios marcados para {who}, así que se muestran todos. Márcalos en la computadora, en Union compliance.",
  "time.you": "ti",
  "time.crewMember": "Miembro de la cuadrilla",
  "time.clock.onTheClock": "En turno · {elapsed}",
  "time.clock.clockedInOn": "Turno iniciado en {job}",
  "time.clock.anotherJob": "otra obra",
  "time.clock.break": "Descanso: {minutes} min",
  "time.clock.minBreak": "{minutes} min de descanso",
  "time.clock.switch": "Cambiar",
  "time.clock.switchToThisJob": "Cambiar a esta obra",
  "time.clock.start": "Comenzar",
  "time.clock.alreadyOn": "Ya tienes un turno iniciado. Marca salida o cambia de obra.",
  "time.clock.nothingToRecord": "No hay nada que registrar: el descanso de {minutes} minutos es igual de largo que el tiempo en el turno. Baja el descanso primero.",
  "time.day.today": "Hoy",
  "time.day.earlier": "Antes",
  "time.locked.approved": "Aprobado · cerrado",
  "time.locked.signed": "Firmado · cerrado",
  "time.dayLocked.signed": "{date} está firmado, así que sus horas están cerradas. La oficina lo puede reabrir en la computadora.",
  "time.dayLocked.approved": "{date} está firmado y aprobado, así que sus horas están cerradas. La oficina lo puede reabrir en la computadora.",
  "time.save.one": "Guardar registro",
  "time.save.many": "Guardar {count} registros",
  "time.hoursRange": "Las horas deben ser más de 0 y máximo 24.",
  "time.pickCraft": "Escoge un oficio.",
  "time.noCostCodes": "Esta obra todavía no tiene códigos de costo, así que estas horas no van en ninguna partida.",
  "time.copyCrew": "Copiar la cuadrilla del {date}",
  "time.field.sameAsEveryone": "{hours} — igual que todos",
  "time.handover.button": "Pasar el teléfono",
  "time.handover.title": "Pasar el teléfono",
  "time.handover.primary": "Pasarlo",
  "time.handover.note": "Va a ver una sola pantalla — sus propias horas de hoy en esta obra, y un lugar para firmar. Nada más del teléfono queda abierto mientras lo tenga.",
  "time.handover.noCrew": "Todavía no hay cuadrilla en esta compañía. Se agregan en la computadora, en la página de Equipo.",
  "time.handover.pin": "PIN para recuperar el teléfono (opcional)",
  "time.handover.pinHint": "4 dígitos",
  "time.handover.pinNote": "Sin PIN, cualquiera que tenga el teléfono lo puede regresar — lo cual casi siempre está bien, porque tú estás ahí parado. Con un PIN, no regresa hasta que lo escribas.",
  "time.alreadySignedBy": "{date} ya está firmado por {name}.",
  "time.noHoursToSign": "No hay horas que firmar en {date}.",
  "time.thatDay": "ese día",
  "time.entries.one": "1 registro · {hours}h",
  "time.entries.many": "{count} registros · {hours}h",
  "time.report.filed": "Reporte diario: entregado",
  "time.report.notFiled": "Reporte diario: todavía sin entregar",
  "time.delays.one": "1 retraso",
  "time.delays.many": "{count} retrasos",
  "time.signing.locks": "Firmar cierra estas horas. Lo que siga esperando por enviarse se manda primero. Si después algo está mal, la oficina reabre el día en la computadora.",
  "time.signing.locksWithReport": "Firmar cierra estas horas, el reporte diario y sus retrasos. Lo que siga esperando por enviarse se manda primero. Si después algo está mal, la oficina reabre el día en la computadora.",

  // drawings-schedule
  "drawings.notOnSite": "La revisión actual no ha llegado a la obra — la cuadrilla está en {label}",
  "drawings.nothingYet": "ninguna todavía",
  "drawings.current": "actual",
  "drawings.onThisPhone": "En este teléfono",
  "drawings.issued": "Emitida el {date}",
  "drawings.received": "recibida el {date}",
  "drawings.notReceived": "no recibida",
  "drawings.open": "Abrir",
  "drawings.saving": "Guardando…",
  "drawings.removeFromPhone": "Quitar del teléfono",
  "drawings.keepOnPhone": "Guardar en el teléfono",
  "drawings.noFile": "No hay archivo registrado para esta revisión",
  "drawings.kept": "{size} de planos guardados en este teléfono",
  "drawings.cantOpen": "No se pudo abrir ese plano.",
  "drawings.cantOpenSaved": "Esta versión todavía no puede abrir un plano guardado — se abre en línea hasta que se vuelva a compilar la app.",
  "drawings.cantDownload": "No se pudo descargar ese plano — inténtalo otra vez donde haya señal.",
  "schedule.today": "Hoy",
  "schedule.past": "pasado",
  "schedule.noHours": "Sin horas registradas",

  // home-today
  "home.greeting.morning": "Buenos días",
  "home.greeting.afternoon": "Buenas tardes",
  "home.greeting.evening": "Buenas noches",
  "home.today": "Hoy",
  "common.loading": "Cargando…",
  "home.empty.notYours.title": "Esta pantalla no es para ti",
  "home.empty.notYours.body": "Inicio es el día en una obra — reportes, fotos, la lista de pendientes, horas — y los registros de campo no son parte de tu puesto. Las obras siguen en la pestaña Obras.",
  "home.empty.noJob.title": "Elige una obra para empezar el día",
  "home.empty.noJob.body": "Cuando estés en una obra, esta pantalla muestra qué está hecho y qué no — y el botón de captura funciona sin preguntarte cuál obra cada vez.",
  "home.offline.nothing": "Sin conexión, y este teléfono todavía no ha cargado esta obra",
  "home.photos.all": "Todas las fotos de hoy",
  "home.photos.open": "Abrir fotos",
  "today.pending.one": "1 cambio sin enviar",
  "today.pending.many": "{count} cambios sin enviar",
  "today.report.filed": "El reporte de hoy ya está entregado",
  "today.report.notFiled": "El reporte de hoy no está entregado",
  "today.time.none": "No hay horas registradas hoy",
  "today.time.hour.onePerson": "{hours} hora registrada hoy, 1 persona",
  "today.time.hour.manyPeople": "{hours} hora registrada hoy, {people} personas",
  "today.time.hours.onePerson": "{hours} horas registradas hoy, 1 persona",
  "today.time.hours.manyPeople": "{hours} horas registradas hoy, {people} personas",
  "today.punch.open.one": "1 pendiente abierto",
  "today.punch.open.many": "{open} pendientes abiertos",
  "today.punch.waiting": "{waiting} esperando verificación",
  "today.punch.openAndWaiting.one": "1 pendiente abierto, {waiting} esperando verificación",
  "today.punch.openAndWaiting.many": "{open} pendientes abiertos, {waiting} esperando verificación",
  "today.punch.clear": "Ya no hay pendientes",
  "today.photos.none": "No hay fotos de hoy",
  "today.photos.one": "1 foto hoy",
  "today.photos.many": "{count} fotos hoy",

  // shared
  "outbox.noReason": "sin motivo",
  "outbox.op.thisJob": "esta obra",
  "outbox.op.dailyReport": "Reporte diario",
  "outbox.op.dailyReportChange": "Cambio a un reporte diario",
  "outbox.op.hours": "{hours} horas",
  "outbox.op.materialOrder": "Pedido de material · {job}",
  "outbox.op.toolboxTalk": "Plática de seguridad · {job} · {date}",
  "outbox.op.incident": "Incidente · {name}",
  "outbox.op.punchItem": "Pendiente · {job}",
  "outbox.op.punchReady": "Pendiente marcado como listo",
  "outbox.op.punchReopened": "Pendiente reabierto",
  "outbox.op.tmTicket": "Ticket de T&M · {job} · {date}",
  "outbox.op.photo": "Foto",
  "outbox.op.delay": "Retraso",
  "outbox.op.signoff": "Hoja de horas firmada por {name}",
  "common.throwAway": "Descartar",
  "common.notSavedItems.one": "1 registro no se guardó",
  "common.notSavedItems.many": "{count} registros no se guardaron",
  "job.chip.on": "En esta obra",
  "job.chip.none": "Sin obra seleccionada",
  "job.chip.choose": "Escoge una para empezar",
  "job.chip.pick": "Escoger",
  "job.chip.a11y": "En {job}. Toca para cambiar de obra.",
  "job.chip.a11yNone": "Escoge una obra",
  "date.yesterday": "Ayer",
  "date.otherDay": "Otro día…",
  "date.previousMonth": "Mes anterior",
  "date.nextMonth": "Mes siguiente",
  "signature.here": "Firma aquí",
  "signature.clear": "Borrar",
  "notYourJob.title": "Tus funciones no incluyen {what}.",
  "notYourJob.body": "El dueño de la cuenta define quién ve qué, en la página de Equipo. No falta nada en este teléfono — esto no es tuyo para ver.",
  "notYourJob.noun.reports": "los reportes diarios",
  "notYourJob.noun.photos": "las fotos de la obra",
  "notYourJob.noun.punch": "las listas de pendientes",
  "notYourJob.noun.time": "los registros de horas",
  "notYourJob.noun.materials": "los pedidos de material",
  "notYourJob.noun.safety": "los registros de seguridad",
  "notYourJob.noun.tickets": "los tickets de T&M",
  "notYourJob.noun.schedule": "el programa de la cuadrilla",
  "notYourJob.noun.drawings": "los planos",
};
