-- Email provenance for the cold-outbound email finder (announced in
-- #prova-build before the push, rule 4). Entirely ADDITIVE: three nullable
-- columns on SalesLead. Every existing lead reads null in all three, which
-- means "nobody has looked", so the deploy before this migration and the one
-- after it both read the table fine.
--
-- Generated by `prisma migrate diff --from-schema-datamodel <committed>
-- --to-schema-datamodel prisma/schema` — a schema-to-schema diff that
-- opens no database connection (see the --shadow-database-url entry in
-- CLAUDE.md for why that matters here).

-- AlterTable
ALTER TABLE "SalesLead" ADD COLUMN     "emailSource" TEXT,
ADD COLUMN     "emailVerifiedAt" TIMESTAMP(3),
ADD COLUMN     "website" TEXT;
