-- The building's gross area, for conceptual estimating before there are
-- drawings to measure.
--
-- PURELY ADDITIVE: one nullable column. Nothing dropped, nothing altered, no
-- existing row touched. Expected to stay null on most jobs — a job with no
-- area simply does not contribute to the benchmark, which is the honest
-- behaviour. The alternative is guessing an area and polluting every future
-- conceptual estimate with the guess.
--
-- THIS IS NOT A TAKEOFF QUANTITY. Every other square-foot figure in this
-- schema is per-line-item (JobLineItem.unit "SF", WallComponentBasis
-- FACE_SQFT, TakeoffMeasurementKind AREA). This is the only project-level
-- one, and multiplying it by a unit price would produce a number that means
-- nothing.
--
-- Generated by schema-to-schema diff. Never --shadow-database-url.

-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "grossAreaSqFt" DECIMAL(12,2);

