import { describe, expect, it } from "vitest";
import {
  companyProfileGaps,
  looksAutoGenerated,
  normalizeEin,
  normalizeWebsite,
  type CompanyProfile,
} from "@/lib/company-profile";

/**
 * The rules behind the company record, executed rather than read.
 *
 * These decide what a federal form and a trust-fund report print, which is
 * the same argument lib/wh347.ts makes for being pure: a rule only
 * reachable through a form is a rule nobody can check.
 */

function company(overrides: Partial<CompanyProfile> = {}): CompanyProfile {
  return {
    name: "Sierra Interior Systems, Inc.",
    dbaName: null,
    ein: "84-1234567",
    hqAddressLine1: "1400 Industrial Way",
    hqAddressLine2: null,
    hqCity: "Longmont",
    hqState: "CO",
    hqZip: "80501",
    phone: null,
    website: null,
    ...overrides,
  };
}

describe("normalizeEin", () => {
  it("stores nine bare digits hyphenated", () => {
    expect(normalizeEin("841234567")).toEqual({ ok: true, value: "84-1234567" });
  });

  it("stores an already-hyphenated EIN unchanged", () => {
    expect(normalizeEin("84-1234567")).toEqual({ ok: true, value: "84-1234567" });
  });

  // The whole reason to normalise: two people typing the same EIN two ways
  // must not produce two different strings on two prints of one month.
  it("stores both accepted forms identically", () => {
    expect(normalizeEin("841234567")).toEqual(normalizeEin("84-1234567"));
    expect(normalizeEin(" 84 - 123 4567 ")).toEqual(normalizeEin("84-1234567"));
  });

  it("treats an empty field as not recorded rather than as an error", () => {
    expect(normalizeEin("")).toEqual({ ok: true, value: null });
    expect(normalizeEin("   ")).toEqual({ ok: true, value: null });
  });

  it("refuses a wrong number of digits and says how many it counted", () => {
    const result = normalizeEin("84-123456");
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error("expected a refusal");
    expect(result.error).toContain("nine digits");
    expect(result.error).toContain("has 8");
  });

  it("refuses letters rather than silently stripping them", () => {
    // Stripping would store nine digits belonging to some other number —
    // a licence or a state account id pasted into the wrong box.
    const result = normalizeEin("CA-841234567");
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error("expected a refusal");
    expect(result.error).toContain("digits only");
  });
});

describe("normalizeWebsite", () => {
  it("adds a scheme to a bare host rather than refusing over one", () => {
    expect(normalizeWebsite("sierrainteriors.com")).toEqual({
      ok: true,
      value: "https://sierrainteriors.com",
    });
  });

  it("keeps an explicit scheme and drops the slash URL parsing adds", () => {
    expect(normalizeWebsite("http://sierrainteriors.com")).toEqual({
      ok: true,
      value: "http://sierrainteriors.com",
    });
    expect(normalizeWebsite("https://sierrainteriors.com/")).toEqual({
      ok: true,
      value: "https://sierrainteriors.com",
    });
  });

  it("keeps a real path", () => {
    expect(normalizeWebsite("sierrainteriors.com/about")).toEqual({
      ok: true,
      value: "https://sierrainteriors.com/about",
    });
  });

  it("treats an empty field as not recorded", () => {
    expect(normalizeWebsite("  ")).toEqual({ ok: true, value: null });
  });

  it("refuses something that is not an address at all", () => {
    for (const raw of ["Sierra Interiors", "not a url", "https://", "::::"]) {
      const result = normalizeWebsite(raw);
      expect(result.ok, `"${raw}" should be refused`).toBe(false);
    }
  });

  it("refuses a host with no dot, which URL() otherwise accepts happily", () => {
    expect(new URL("https://sierrainteriors").hostname).toBe("sierrainteriors");
    expect(normalizeWebsite("https://sierrainteriors").ok).toBe(false);
  });

  it("refuses a scheme that is not http(s), naming which are allowed", () => {
    const result = normalizeWebsite("ftp://files.sierrainteriors.com");
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error("expected a refusal");
    expect(result.error).toContain("http://");
  });
});

describe("looksAutoGenerated", () => {
  // Both spellings requireCompanyContext can produce (lib/auth.ts).
  it("recognises what sign-up invents", () => {
    expect(looksAutoGenerated("Cyrus's Company")).toBe(true);
    expect(looksAutoGenerated("My Company")).toBe(true);
  });

  it("leaves a real company name alone", () => {
    expect(looksAutoGenerated("Sierra Interior Systems, Inc.")).toBe(false);
    expect(looksAutoGenerated("Company Drywall LLC")).toBe(false);
  });
});

describe("companyProfileGaps", () => {
  it("finds nothing to report on a complete record", () => {
    expect(companyProfileGaps(company())).toEqual([]);
  });

  it("flags the name sign-up invented, and says where it prints", () => {
    const gaps = companyProfileGaps(company({ name: "Cyrus's Company" }));
    expect(gaps.map((g) => g.field)).toEqual(["name"]);
    expect(gaps[0].consequence).toContain("WH-347");
    expect(gaps[0].consequence).toContain("Cyrus's Company");
  });

  it("flags a missing EIN with what the remittance sheet does instead", () => {
    const gaps = companyProfileGaps(company({ ein: null }));
    expect(gaps.map((g) => g.field)).toEqual(["ein"]);
    expect(gaps[0].consequence).toContain("remittance");
  });

  it("treats a whitespace-only EIN as missing, the way the sheet does", () => {
    expect(companyProfileGaps(company({ ein: "   " })).map((g) => g.field)).toEqual(["ein"]);
  });

  // The documents treat a partial address as no address. This asserts the
  // gap list agrees, field by field, rather than restating the rule.
  it("flags a partial address, whichever of the four parts is absent", () => {
    for (const missing of ["hqAddressLine1", "hqCity", "hqState", "hqZip"] as const) {
      const gaps = companyProfileGaps(company({ [missing]: null }));
      expect(gaps.map((g) => g.field), `${missing} missing`).toEqual(["address"]);
    }
  });

  it("does not flag a missing suite line, which is genuinely optional", () => {
    expect(companyProfileGaps(company({ hqAddressLine2: null }))).toEqual([]);
  });

  // A gap list that names every empty field trains the reader to ignore it.
  it("does not flag phone or website, which no document prints", () => {
    expect(companyProfileGaps(company({ phone: null, website: null }))).toEqual([]);
  });

  it("reports every gap on an untouched sign-up record, not just the first", () => {
    const fresh = companyProfileGaps({
      name: "Cyrus's Company",
      dbaName: null,
      ein: null,
      hqAddressLine1: null,
      hqAddressLine2: null,
      hqCity: null,
      hqState: null,
      hqZip: null,
      phone: null,
      website: null,
    });
    expect(fresh.map((g) => g.field)).toEqual(["name", "ein", "address"]);
  });
});
