-- Bid-form compliance: the paperwork that decides whether anybody reads the
-- number. Two new tables and one enum.
--
-- PURELY ADDITIVE. Nothing dropped, no existing column altered, no existing
-- row touched. Both tables CASCADE from BidInvitation (an addendum received
-- for a bid is part of that bid's working out, not a record that should
-- outlive it) and neither carries a jobId, so neither needs registering in
-- the cleanup scripts — the same shape as BidLine and BidQuote.
--
-- Generated by schema-to-schema diff (--from-schema-datamodel /
-- --to-schema-datamodel), which opens no database connection. Never
-- --shadow-database-url: that DROPS AND RECREATES whatever it is pointed at,
-- and on 2026-09-18 it was pointed at a real one.

-- CreateEnum
CREATE TYPE "BidRequirementKind" AS ENUM ('BID_BOND', 'SIGNED_BID_FORM', 'SUBCONTRACTOR_LIST', 'INSURANCE_CERTIFICATE', 'PREQUALIFICATION', 'PARTICIPATION_FORMS', 'OTHER');

-- CreateTable
CREATE TABLE "BidAddendum" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "bidInvitationId" TEXT NOT NULL,
    "reference" TEXT NOT NULL,
    "issuedOn" TIMESTAMP(3),
    "acknowledgedOn" TIMESTAMP(3),
    "affectsPricedScope" BOOLEAN NOT NULL DEFAULT false,
    "impactNote" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BidAddendum_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BidRequirement" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "bidInvitationId" TEXT NOT NULL,
    "kind" "BidRequirementKind" NOT NULL,
    "label" TEXT NOT NULL,
    "required" BOOLEAN NOT NULL DEFAULT true,
    "satisfiedOn" TIMESTAMP(3),
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BidRequirement_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "BidAddendum_bidInvitationId_idx" ON "BidAddendum"("bidInvitationId");

-- CreateIndex
CREATE INDEX "BidAddendum_companyId_idx" ON "BidAddendum"("companyId");

-- CreateIndex
CREATE INDEX "BidRequirement_bidInvitationId_idx" ON "BidRequirement"("bidInvitationId");

-- CreateIndex
CREATE INDEX "BidRequirement_companyId_idx" ON "BidRequirement"("companyId");

-- AddForeignKey
ALTER TABLE "BidAddendum" ADD CONSTRAINT "BidAddendum_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BidAddendum" ADD CONSTRAINT "BidAddendum_bidInvitationId_fkey" FOREIGN KEY ("bidInvitationId") REFERENCES "BidInvitation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BidRequirement" ADD CONSTRAINT "BidRequirement_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BidRequirement" ADD CONSTRAINT "BidRequirement_bidInvitationId_fkey" FOREIGN KEY ("bidInvitationId") REFERENCES "BidInvitation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

