import { SALES_SIGNAL_KINDS, type SalesSignalKind } from "@/lib/sales-qualification";
import { tradeScopeLabel } from "@/lib/trade-scopes";
import { money } from "@/lib/money";
import { looksCutOff, type ListedSub, type SubListingParse } from "./parse";

/**
 * TURNING ONE LISTED SUBCONTRACTOR INTO SIGNALS A PERSON CAN CHECK.
 *
 * `parse.ts` reads a public bid or award document. This decides what that row
 * is EVIDENCE OF, in the vocabulary `lib/sales-qualification.ts` already has.
 *
 * ── WHY THIS IS THE HIGHEST-LEVERAGE PRODUCER OF SIGNALS IN THE APP ──
 *
 * The band needs `TRADE` and `GEOGRAPHY` confirmed to leave *Too thin to call*,
 * and one of `PROJECT` or `GC_RELATIONSHIP` on top of that to reach *Call this
 * one*. A single row of a subcontractor listing can carry **all four**: the
 * portion of work is the trade, the city is the geography, the project is the
 * project, and the bidding contractor the row sat under is the GC.
 *
 * So one pasted award packet takes a company nobody here had heard of to a
 * briefed, sourced, call-ready lead — and the opening line on the call is a
 * sentence quoting a document the man himself filed. That is the whole
 * acquisition motion in one function, which is why its correctness matters more
 * than its size suggests.
 *
 * ── EVERY CLAIM IS THE DOCUMENT'S WORDS, NOT A SENTENCE ABOUT THEM ──
 *
 * The rule from the GTM study is that *a specific email that is wrong is
 * disqualifying* — worse than a vague one, because being wrong about a man's own
 * job costs the relationship rather than the reply. So no claim here asserts
 * anything the document did not say:
 *
 *   - the trade claim quotes `portionOfWork` verbatim and only ADDS our scope
 *     name when `tradeScopeFor` matched one;
 *   - the project claim names the project, the prime and the amount only when
 *     the document printed them, and degrades to a shorter true sentence when it
 *     did not;
 *   - every claim ends with the line number, so the person reviewing it can put
 *     a finger on the row. `sourceUrl` on the signal is the document; the line
 *     is where in it.
 *
 * Nothing is inferred, nothing is rounded, and no sentence is generated by a
 * model. There is deliberately no model call anywhere in this directory — see
 * the note on lanes in the action.
 *
 * ── THE TOTAL RECORD IS DOING TWO JOBS ──
 *
 * `CLAIM_FOR` is a `Record<SalesSignalKind, …>` over the canonical kind list, so
 * a ninth signal kind cannot be added without deciding here whether a bid
 * listing is evidence of it. A kind this document cannot speak to returns
 * `null` and is dropped — which is a decision on the record rather than an
 * omission.
 *
 * It also keeps every kind name an IDENTIFIER rather than a quoted string.
 * `salesQualificationPurity.test.ts` fails the build on a quoted
 * `GC_RELATIONSHIP` anywhere but `lib/sales-qualification.ts`, because the kind
 * list must have exactly one home — so iterating the imported list and indexing
 * this record is not a stylistic choice, it is the only shape that compiles.
 */

/** A signal this reader proposes. Deliberately not a Prisma shape. */
export type ProposedSignal = {
  kind: SalesSignalKind;
  claim: string;
  /** The line of the pasted document this came from, for the reviewer. */
  line: number;
};

/**
 * WHETHER THE PRIME WHO FILED THIS FORM ACTUALLY WON.
 *
 * The most expensive thing learned while building this, and it is not in the
 * code — it is in the statute. California's listing (Public Contract Code
 * §4104) is filed **with the bid**, by **every** prime bidder. So one project
 * with five primes names five drywall subs: one who is about to get the work
 * and four who are not.
 *
 * The first version of the claim below read "On Lincoln Elementary, under
 * Swinerton" and it would have been a false sentence for four subs in five —
 * congratulating a man on a job he lost, which in a trade this small is not a
 * lost reply, it is a lost relationship. **A listing is evidence of a BID, and
 * only an award document is evidence of a JOB.**
 *
 * So the outcome is never inferred, never defaulted to the hopeful value, and
 * never parsed out of the listing — it is declared by the person importing,
 * because they are the one looking at the document that says so. `UNKNOWN` is
 * the default and produces a sentence that is true either way.
 */
export const PRIME_OUTCOMES = ["AWARDED", "UNKNOWN"] as const;
export type PrimeOutcome = (typeof PRIME_OUTCOMES)[number];

/** A trimmed value, or null for a blank one — what `blank` means in `sales.ts`. */
function blank(value: string | null | undefined): string | null {
  const trimmed = value?.trim();
  return trimmed ? trimmed : null;
}

/**
 * WHICH GENERAL CONTRACTOR LISTED THIS SUBCONTRACTOR — the row's own bidder
 * first, the page-level prime only as a fallback.
 *
 * **This file read `header.prime` ALONE until 2026-10-05, and that is the only
 * fact in the whole feature the sales call is made of.** The opening line is
 * "I saw <GC> listed you on <job>", and it is what moves a lead from *Worth a
 * call — nothing specific to open with yet* to *Call this one*. `parse.ts` reads
 * the bidding contractor PER ROW, because the common published shape is a bid
 * summary naming every prime who bid — and `readHeader` deliberately NULLS
 * `header.prime` when a page names more than one, since nothing in a flat paste
 * says which prime a given row sits under. The two facts together meant that on
 * exactly the documents per-row attribution was built for, this file either:
 *
 *   - named no GC at all (`header.prime` nulled by the conflict, so
 *     `GC_RELATIONSHIP` returned null and `PROJECT` read "Named on a bid for
 *     Riverbend Transit Center" — the row knowing the bidder and the sentence
 *     not saying it), or
 *   - named the WRONG one: a packet labelling `Prime: <first bidder>` at the top
 *     and then printing further bidders' own tables raises no conflict, so every
 *     row in every later block was attributed to the first prime. That is a
 *     specific, checkable, false sentence about the reader's own work, which is
 *     the one thing the GTM study calls disqualifying — the exact failure the
 *     `readHeader` and `PRIME_OUTCOMES` comments were written about, arriving
 *     through the row instead of through the header or the outcome.
 *
 * The stored column has been right the whole time: `sales.ts` writes
 * `listedByGc: blank(row.listedBy) ?? blank(header.prime)`. **The sentence is the
 * product and the column is only its storage**, so the claim had to learn the
 * same precedence — and per #526, a second COPY of that precedence is the defect
 * this repo keeps paying for, so this is exported for `sales.ts` to call rather
 * than restated there. Until it does, the two agree by assertion:
 * `signals.test.ts` reads the precedence out of `sales.ts`'s own source and fails
 * if it drifts from this function.
 *
 * Falling back to `header.prime` can never attribute the wrong GC on a
 * multi-prime page, for the reason `listingProvenance` gives: there is nothing to
 * fall back TO in exactly the case where guessing would be wrong.
 */
export function listedByGcFor(
  sub: Pick<ListedSub, "listedBy">,
  header: Pick<SubListingParse["header"], "prime">,
): string | null {
  return blank(sub.listedBy) ?? blank(header.prime);
}

/**
 * The GC as a claim may print it: marked when the name visibly does not finish.
 *
 * The same treatment `projectPhrase` gives a wrapped project and the TRADE claim
 * gives a wrapped scope, for the same reason and on the half of the sentence that
 * names a man by name. `parse.ts` joins a bidder's name across two lines only
 * when the first ends in a comma, so "Hutchinson and" / "Sons Builders" leaves
 * the fragment behind — and "I saw Hutchinson and listed you" is worse than
 * saying nothing, because it is read aloud.
 */
function gcPhrase(
  sub: Pick<ListedSub, "listedBy">,
  header: Pick<SubListingParse["header"], "prime">,
): string | null {
  const gc = listedByGcFor(sub, header);
  if (!gc) return null;
  return looksCutOff(gc) ? `${gc}\u2026` : gc;
}

/** Everything a claim sentence is allowed to draw on. */
type ClaimContext = {
  sub: ListedSub;
  header: SubListingParse["header"];
  primeOutcome: PrimeOutcome;
};

/** "line 14" — appended to every claim so a reviewer can go and look. */
function atLine(line: number): string {
  return ` (line ${line} of the listing)`;
}

/**
 * The project half of a sentence, built only from what the document printed.
 *
 * Four shapes rather than one template with holes in it: a sentence reading
 * "listed on under for" because two fields were blank is worse than a shorter
 * sentence, and this is read aloud on a phone call.
 */
function projectPhrase(header: SubListingParse["header"]): string | null {
  // A wrapped project name is marked, exactly as a wrapped portion of work is.
  // The TRADE claim has hedged this since the first review and the two claims
  // that name the man's JOB did not — so a project truncated at a conjunction
  // was read down a telephone as though it were the whole name. `parse.ts`
  // raises a problem about it too; this is the half that reaches the sentence.
  const raw = header.project?.trim() || null;
  const project = raw && looksCutOff(raw) ? `${raw}…` : raw;
  const agency = header.agency?.trim() || null;
  if (project && agency) return `${project} (${agency})`;
  return project ?? agency ?? null;
}

const CLAIM_FOR: Record<SalesSignalKind, (context: ClaimContext) => string | null> = {
  TRADE: ({ sub }) => {
    if (!sub.portionOfWork) return null;
    const scope = tradeScopeLabel(sub.tradeScope);

    // A scope that wrapped onto the next line parses as a whole phrase ending
    // in "and", and the first version quoted it verbatim. The row carried a
    // concern about it and the claim went out unchanged — so the one thing that
    // reaches a telephone was the one thing the warning did not reach. It is
    // marked as a fragment now, in the claim itself.
    const quoted = looksCutOff(sub.portionOfWork)
      ? `Listed for "${sub.portionOfWork}…", which runs on past the end of the line`
      : `Listed for "${sub.portionOfWork}"`;

    return scope
      ? `${quoted} — that is ${scope}${atLine(sub.line)}`
      : `${quoted}${atLine(sub.line)}`;
  },

  GEOGRAPHY: ({ sub }) =>
    sub.city ? `Listed out of ${sub.city}${atLine(sub.line)}` : null,

  LICENCE: ({ sub }) => {
    const parts: string[] = [];
    if (sub.licence) parts.push(`licence ${sub.licence}`);
    if (sub.registration) parts.push(`public-works registration ${sub.registration}`);
    if (parts.length === 0) return null;
    return `Listed with ${parts.join(" and ")}${atLine(sub.line)}`;
  },

  PROJECT: ({ sub, header, primeOutcome }) => {
    const where = projectPhrase(header);
    if (!where) return null;
    const prime = gcPhrase(sub, header);

    // Awarded: the job is theirs. Unknown: they are on a BID for it, which is
    // all the listing proves and all this sentence may say.
    const opening =
      primeOutcome === "AWARDED"
        ? prime
          ? `On ${where}, under ${prime}`
          : `On ${where}`
        : prime
          ? `Named on ${prime}'s bid for ${where}`
          : `Named on a bid for ${where}`;

    const clauses: string[] = [opening];
    // Only when the document printed one. California's §4104 has no dollar
    // field, so on a CA listing this is correctly absent — and rendering an
    // estimate here would be the one specificity that disqualifies, since money
    // is the thing they would be hiring us for.
    if (sub.amount !== null) clauses.push(`listed at ${money(sub.amount)}`);
    else if (sub.percentOfBid !== null) clauses.push(`listed at ${sub.percentOfBid}% of the bid`);
    if (header.bidDate?.trim()) clauses.push(`bid opened ${header.bidDate.trim()}`);

    /**
     * WHAT IS KNOWN, PLUS WHAT IS DOUBTFUL — not silence, and not a guess.
     *
     * With no GC resolvable the project is still a real, sourced, checkable fact
     * and worth proposing. What must not happen is a reviewer reading "Named on a
     * bid for Riverbend Transit Center" and supplying the page's own prime from
     * memory, which is how an unattributed row becomes a wrong name on a call. So
     * the uncertainty is named in the sentence that carries it. This is the
     * architecture's own rule — every signal lands PROPOSED for a person to
     * confirm, so claim it and say what is doubtful beats refusing it.
     *
     * `GC_RELATIONSHIP` stays silent in the same case, and that is not an
     * inconsistency: a confirmed GC_RELATIONSHIP carrying no GC's name would move
     * the band to *Call this one* on nothing anybody can ring.
     */
    const doubts: string[] = [];
    if (!prime) doubts.push("the paste does not say which prime bidder listed them");
    if (primeOutcome !== "AWARDED") doubts.push("the listing does not say whether that bid won");
    const tail = doubts.length === 0 ? "" : ` — ${doubts.join(", and ")}`;

    return `${clauses.join(", ")}${tail}${atLine(sub.line)}`;
  },

  GC_RELATIONSHIP: ({ sub, header, primeOutcome }) => {
    /* The row's own bidder first. Nothing is invented when neither is known: the
       labelled-column form refuses attribution outright and a page naming several
       primes has its header nulled, and in both cases this kind has nothing to
       say — a relationship claim that names no contractor is a rumour. */
    const prime = gcPhrase(sub, header);
    if (!prime) return null;
    const where = projectPhrase(header);

    // True whether or not the bid won: the prime chose to put this sub on their
    // form, which is the relationship. "Works under" is reserved for an award.
    if (primeOutcome === "AWARDED") {
      return where
        ? `Works under ${prime} — their subcontractor on ${where}${atLine(sub.line)}`
        : `Works under ${prime}, who listed them as a subcontractor${atLine(sub.line)}`;
    }
    return where
      ? `${prime} listed them as their subcontractor when bidding ${where}${atLine(sub.line)}`
      : `${prime} listed them as their subcontractor on a bid${atLine(sub.line)}`;
  },

  /**
   * The three a subcontractor listing cannot speak to, each `null` on purpose
   * rather than by omission.
   *
   * SIZE is the tempting one and the most important to refuse: a dollar value
   * on one scope of one job says nothing about how many people a company
   * employs, and a lead banded on an invented headcount is exactly the
   * "confident fact wearing a citation" failure `lib/research/bidResearch.eval.ts`
   * is built around. The amount belongs in the PROJECT claim, where it is
   * true, and nowhere else.
   */
  SIZE: () => null,
  UNION: () => null,
  TECH: () => null,
};

/**
 * Every signal a listed subcontractor is evidence of, in the canonical kind
 * order, with the kinds this document cannot support dropped.
 */
export function signalsForSub(
  sub: ListedSub,
  header: SubListingParse["header"],
  primeOutcome: PrimeOutcome = "UNKNOWN",
): ProposedSignal[] {
  const proposed: ProposedSignal[] = [];
  for (const kind of SALES_SIGNAL_KINDS) {
    const claim = CLAIM_FOR[kind]({ sub, header, primeOutcome });
    if (claim) proposed.push({ kind, claim, line: sub.line });
  }
  return proposed;
}

/**
 * Should this row be imported?
 *
 * A pure function with a test, for a rule small enough that nobody would think
 * to write one — which is exactly why it shipped broken. The screen held a
 * `skipped` set and derived `checked` as `!skipped[line] && tradeScope !== null`,
 * so for a row whose trade did not match, `checked` was ALREADY false: ticking
 * it deleted a key that had never been set, the value recomputed to false, and
 * the box snapped back. An inert control, with nothing on screen saying so.
 *
 * The fix is that an explicit choice always wins and the trade match is only the
 * DEFAULT. Stated as a function so the two cases cannot drift apart again.
 */
export function shouldInclude(
  row: { tradeScope: string | null },
  explicit: boolean | undefined,
): boolean {
  return explicit ?? row.tradeScope !== null;
}

/**
 * HOW MANY SUBCONTRACTORS ONE IMPORT MAY CARRY, AND THE SENTENCE THAT REFUSES
 * MORE — in one place, read by the server action and by the review screen.
 *
 * The cap is not a performance limit. It is there because the whole feature's
 * claim is that a person LOOKED at these rows, and a hundred-row paste ticked
 * through in one click is that claim being false.
 *
 * It lived as a private `MAX_LISTING_ROWS` in `lib/actions/sales.ts` with the
 * sentence written inline, which made the screen unable to say anything before
 * the round trip: the submit button promised "Add 94 subcontractors", the server
 * refused all 94, and the reviewer learned the limit from an error. The obvious
 * fix — a `60` in the component too — is the second-list failure CLAUDE.md
 * records, and it would have been two numbers AND two sentences free to drift.
 *
 * So the decision is a function rather than a constant, and both callers ask it.
 * `null` means "this many is fine". A string is the refusal, and it is the SAME
 * string in both places by construction, not by anybody keeping them in step.
 */
export const MAX_LISTING_ROWS = 60;

export function tooManyRows(count: number): string | null {
  if (count <= MAX_LISTING_ROWS) return null;
  return `That is ${count} subcontractors at once. Import up to ${MAX_LISTING_ROWS} so the reading stays something a person has actually looked at.`;
}

/**
 * A one-line summary of what importing a row would do, for the review screen.
 *
 * Phrased as a count of signals rather than a promise about the band, because
 * every signal lands PROPOSED and a band that moves only once a person confirms
 * them is the one thing this feature must not appear to shortcut.
 */
export function importSummaryFor(
  sub: ListedSub,
  header: SubListingParse["header"],
  primeOutcome: PrimeOutcome = "UNKNOWN",
): string {
  const count = signalsForSub(sub, header, primeOutcome).length;
  if (count === 0) return "Nothing here to propose — the row carries no checkable fact";
  return `${count} signal${count === 1 ? "" : "s"} to check`;
}

/**
 * A ROW'S IDENTITY WITHIN ONE READING — WHICH IS NOT ITS LINE NUMBER.
 *
 * `SubListingImport.tsx` used to key the selection on `row.line`, and
 * `importSubListing` used to resolve it the same way, on the stated grounds that
 * a line number is "the only thing two parses of the same document are
 * guaranteed to agree about". The first half of that is still true and this
 * function keeps it. The second half was an assumption nobody had measured, and
 * it is FALSE: `readLabelledColumnsForm` emits ONE ROW PER BIDDER COLUMN and
 * stamps every one of them with the slot's own `firstLine` (`parse.ts`, the
 * labelled-column reader), because that is honestly where they are — the
 * document really does print four firms across one line.
 *
 * What that cost, measured against this repo's own fixtures rather than argued:
 * `ALIGNED` parses to two rows both on line 3 and `RAGGED` to five rows on lines
 * `[3,3,3,8,8]`. The screen posted `"3,3"`, the server deduplicated it to one
 * line, filtered `parsed.rows` back to two, and refused on
 * `chosen.length !== unique.length` with "the listing does not read the same way
 * now as it did on screen — paste it again". Re-pasting reproduces it exactly,
 * because the reader is deterministic. **So a multi-bidder labelled-column
 * listing could be read on screen and never imported, with the refusal telling
 * the reviewer to do the one thing that cannot help.** That is the shape the
 * labelled reader was written FOR — the real documents it was built from print
 * four columns across one slot.
 *
 * Three quieter faults of the same cause, all gone with it: `chosen[row.line]`
 * and `attach[row.line]` ALIASED across every bidder column of a slot, so one
 * tick ticked several firms and one "Already a lead?" choice applied to all of
 * them; and `<li key={row.line}>` repeated a React key.
 *
 * The key is `line.ordinal`, the ordinal counting rows that share a line in
 * reading order. It is derived from the reading alone, so two parses of the same
 * text agree on it exactly as much as they agreed on the line — the property the
 * old scheme was chosen for, kept, with uniqueness added. It is deliberately NOT
 * a field on `ListedSub`: identity belongs to a READING, provenance belongs to
 * the row, and `line` is still what every claim quotes.
 *
 * Asked by the screen and by the server, like `tooManyRows` and for the same
 * reason — two implementations of an identity scheme is the second-list failure
 * this repo keeps paying for.
 */
export function rowKeysFor(rows: readonly { line: number }[]): string[] {
  const seen = new Map<number, number>();
  return rows.map((row) => {
    const ordinal = seen.get(row.line) ?? 0;
    seen.set(row.line, ordinal + 1);
    return `${row.line}.${ordinal}`;
  });
}
