import { SALES_SIGNAL_KINDS, type SalesSignalKind } from "@/lib/sales-qualification";
import { tradeScopeLabel } from "@/lib/trade-scopes";
import { money } from "@/lib/money";
import { looksCutOff, type ListedSub, type SubListingParse } from "./parse";

/**
 * TURNING ONE LISTED SUBCONTRACTOR INTO SIGNALS A PERSON CAN CHECK.
 *
 * `parse.ts` reads a public bid or award document. This decides what that row
 * is EVIDENCE OF, in the vocabulary `lib/sales-qualification.ts` already has.
 *
 * ── WHY THIS IS THE HIGHEST-LEVERAGE PRODUCER OF SIGNALS IN THE APP ──
 *
 * The band needs `TRADE` and `GEOGRAPHY` confirmed to leave *Too thin to call*,
 * and one of `PROJECT` or `GC_RELATIONSHIP` on top of that to reach *Call this
 * one*. A single row of a subcontractor listing can carry **all four**: the
 * portion of work is the trade, the city is the geography, the project is the
 * project, and the prime named at the top of the same document is the GC.
 *
 * So one pasted award packet takes a company nobody here had heard of to a
 * briefed, sourced, call-ready lead — and the opening line on the call is a
 * sentence quoting a document the man himself filed. That is the whole
 * acquisition motion in one function, which is why its correctness matters more
 * than its size suggests.
 *
 * ── EVERY CLAIM IS THE DOCUMENT'S WORDS, NOT A SENTENCE ABOUT THEM ──
 *
 * The rule from the GTM study is that *a specific email that is wrong is
 * disqualifying* — worse than a vague one, because being wrong about a man's own
 * job costs the relationship rather than the reply. So no claim here asserts
 * anything the document did not say:
 *
 *   - the trade claim quotes `portionOfWork` verbatim and only ADDS our scope
 *     name when `tradeScopeFor` matched one;
 *   - the project claim names the project, the prime and the amount only when
 *     the document printed them, and degrades to a shorter true sentence when it
 *     did not;
 *   - every claim ends with the line number, so the person reviewing it can put
 *     a finger on the row. `sourceUrl` on the signal is the document; the line
 *     is where in it.
 *
 * Nothing is inferred, nothing is rounded, and no sentence is generated by a
 * model. There is deliberately no model call anywhere in this directory — see
 * the note on lanes in the action.
 *
 * ── THE TOTAL RECORD IS DOING TWO JOBS ──
 *
 * `CLAIM_FOR` is a `Record<SalesSignalKind, …>` over the canonical kind list, so
 * a ninth signal kind cannot be added without deciding here whether a bid
 * listing is evidence of it. A kind this document cannot speak to returns
 * `null` and is dropped — which is a decision on the record rather than an
 * omission.
 *
 * It also keeps every kind name an IDENTIFIER rather than a quoted string.
 * `salesQualificationPurity.test.ts` fails the build on a quoted
 * `GC_RELATIONSHIP` anywhere but `lib/sales-qualification.ts`, because the kind
 * list must have exactly one home — so iterating the imported list and indexing
 * this record is not a stylistic choice, it is the only shape that compiles.
 */

/** A signal this reader proposes. Deliberately not a Prisma shape. */
export type ProposedSignal = {
  kind: SalesSignalKind;
  claim: string;
  /** The line of the pasted document this came from, for the reviewer. */
  line: number;
};

/**
 * WHETHER THE PRIME WHO FILED THIS FORM ACTUALLY WON.
 *
 * The most expensive thing learned while building this, and it is not in the
 * code — it is in the statute. California's listing (Public Contract Code
 * §4104) is filed **with the bid**, by **every** prime bidder. So one project
 * with five primes names five drywall subs: one who is about to get the work
 * and four who are not.
 *
 * The first version of the claim below read "On Lincoln Elementary, under
 * Swinerton" and it would have been a false sentence for four subs in five —
 * congratulating a man on a job he lost, which in a trade this small is not a
 * lost reply, it is a lost relationship. **A listing is evidence of a BID, and
 * only an award document is evidence of a JOB.**
 *
 * So the outcome is never inferred, never defaulted to the hopeful value, and
 * never parsed out of the listing — it is declared by the person importing,
 * because they are the one looking at the document that says so. `UNKNOWN` is
 * the default and produces a sentence that is true either way.
 */
export const PRIME_OUTCOMES = ["AWARDED", "UNKNOWN"] as const;
export type PrimeOutcome = (typeof PRIME_OUTCOMES)[number];

/** Everything a claim sentence is allowed to draw on. */
type ClaimContext = {
  sub: ListedSub;
  header: SubListingParse["header"];
  primeOutcome: PrimeOutcome;
};

/** "line 14" — appended to every claim so a reviewer can go and look. */
function atLine(line: number): string {
  return ` (line ${line} of the listing)`;
}

/**
 * The project half of a sentence, built only from what the document printed.
 *
 * Four shapes rather than one template with holes in it: a sentence reading
 * "listed on under for" because two fields were blank is worse than a shorter
 * sentence, and this is read aloud on a phone call.
 */
function projectPhrase(header: SubListingParse["header"]): string | null {
  // A wrapped project name is marked, exactly as a wrapped portion of work is.
  // The TRADE claim has hedged this since the first review and the two claims
  // that name the man's JOB did not — so a project truncated at a conjunction
  // was read down a telephone as though it were the whole name. `parse.ts`
  // raises a problem about it too; this is the half that reaches the sentence.
  const raw = header.project?.trim() || null;
  const project = raw && looksCutOff(raw) ? `${raw}…` : raw;
  const agency = header.agency?.trim() || null;
  if (project && agency) return `${project} (${agency})`;
  return project ?? agency ?? null;
}

const CLAIM_FOR: Record<SalesSignalKind, (context: ClaimContext) => string | null> = {
  TRADE: ({ sub }) => {
    if (!sub.portionOfWork) return null;
    const scope = tradeScopeLabel(sub.tradeScope);

    // A scope that wrapped onto the next line parses as a whole phrase ending
    // in "and", and the first version quoted it verbatim. The row carried a
    // concern about it and the claim went out unchanged — so the one thing that
    // reaches a telephone was the one thing the warning did not reach. It is
    // marked as a fragment now, in the claim itself.
    const quoted = looksCutOff(sub.portionOfWork)
      ? `Listed for "${sub.portionOfWork}…", which runs on past the end of the line`
      : `Listed for "${sub.portionOfWork}"`;

    return scope
      ? `${quoted} — that is ${scope}${atLine(sub.line)}`
      : `${quoted}${atLine(sub.line)}`;
  },

  GEOGRAPHY: ({ sub }) =>
    sub.city ? `Listed out of ${sub.city}${atLine(sub.line)}` : null,

  LICENCE: ({ sub }) => {
    const parts: string[] = [];
    if (sub.licence) parts.push(`licence ${sub.licence}`);
    if (sub.registration) parts.push(`public-works registration ${sub.registration}`);
    if (parts.length === 0) return null;
    return `Listed with ${parts.join(" and ")}${atLine(sub.line)}`;
  },

  PROJECT: ({ sub, header, primeOutcome }) => {
    const where = projectPhrase(header);
    if (!where) return null;
    const prime = header.prime?.trim();

    // Awarded: the job is theirs. Unknown: they are on a BID for it, which is
    // all the listing proves and all this sentence may say.
    const opening =
      primeOutcome === "AWARDED"
        ? prime
          ? `On ${where}, under ${prime}`
          : `On ${where}`
        : prime
          ? `Named on ${prime}'s bid for ${where}`
          : `Named on a bid for ${where}`;

    const clauses: string[] = [opening];
    // Only when the document printed one. California's §4104 has no dollar
    // field, so on a CA listing this is correctly absent — and rendering an
    // estimate here would be the one specificity that disqualifies, since money
    // is the thing they would be hiring us for.
    if (sub.amount !== null) clauses.push(`listed at ${money(sub.amount)}`);
    else if (sub.percentOfBid !== null) clauses.push(`listed at ${sub.percentOfBid}% of the bid`);
    if (header.bidDate?.trim()) clauses.push(`bid opened ${header.bidDate.trim()}`);

    const tail =
      primeOutcome === "AWARDED"
        ? ""
        : " — the listing does not say whether that bid won";

    return `${clauses.join(", ")}${tail}${atLine(sub.line)}`;
  },

  GC_RELATIONSHIP: ({ sub, header, primeOutcome }) => {
    const prime = header.prime?.trim();
    if (!prime) return null;
    const where = projectPhrase(header);

    // True whether or not the bid won: the prime chose to put this sub on their
    // form, which is the relationship. "Works under" is reserved for an award.
    if (primeOutcome === "AWARDED") {
      return where
        ? `Works under ${prime} — their subcontractor on ${where}${atLine(sub.line)}`
        : `Works under ${prime}, who listed them as a subcontractor${atLine(sub.line)}`;
    }
    return where
      ? `${prime} listed them as their subcontractor when bidding ${where}${atLine(sub.line)}`
      : `${prime} listed them as their subcontractor on a bid${atLine(sub.line)}`;
  },

  /**
   * The three a subcontractor listing cannot speak to, each `null` on purpose
   * rather than by omission.
   *
   * SIZE is the tempting one and the most important to refuse: a dollar value
   * on one scope of one job says nothing about how many people a company
   * employs, and a lead banded on an invented headcount is exactly the
   * "confident fact wearing a citation" failure `lib/research/bidResearch.eval.ts`
   * is built around. The amount belongs in the PROJECT claim, where it is
   * true, and nowhere else.
   */
  SIZE: () => null,
  UNION: () => null,
  TECH: () => null,
};

/**
 * Every signal a listed subcontractor is evidence of, in the canonical kind
 * order, with the kinds this document cannot support dropped.
 */
export function signalsForSub(
  sub: ListedSub,
  header: SubListingParse["header"],
  primeOutcome: PrimeOutcome = "UNKNOWN",
): ProposedSignal[] {
  const proposed: ProposedSignal[] = [];
  for (const kind of SALES_SIGNAL_KINDS) {
    const claim = CLAIM_FOR[kind]({ sub, header, primeOutcome });
    if (claim) proposed.push({ kind, claim, line: sub.line });
  }
  return proposed;
}

/**
 * Should this row be imported?
 *
 * A pure function with a test, for a rule small enough that nobody would think
 * to write one — which is exactly why it shipped broken. The screen held a
 * `skipped` set and derived `checked` as `!skipped[line] && tradeScope !== null`,
 * so for a row whose trade did not match, `checked` was ALREADY false: ticking
 * it deleted a key that had never been set, the value recomputed to false, and
 * the box snapped back. An inert control, with nothing on screen saying so.
 *
 * The fix is that an explicit choice always wins and the trade match is only the
 * DEFAULT. Stated as a function so the two cases cannot drift apart again.
 */
export function shouldInclude(
  row: { tradeScope: string | null },
  explicit: boolean | undefined,
): boolean {
  return explicit ?? row.tradeScope !== null;
}

/**
 * A one-line summary of what importing a row would do, for the review screen.
 *
 * Phrased as a count of signals rather than a promise about the band, because
 * every signal lands PROPOSED and a band that moves only once a person confirms
 * them is the one thing this feature must not appear to shortcut.
 */
export function importSummaryFor(
  sub: ListedSub,
  header: SubListingParse["header"],
  primeOutcome: PrimeOutcome = "UNKNOWN",
): string {
  const count = signalsForSub(sub, header, primeOutcome).length;
  if (count === 0) return "Nothing here to propose — the row carries no checkable fact";
  return `${count} signal${count === 1 ? "" : "s"} to check`;
}
