-- Reading a bid addendum: what the GC's letter says it changed.
--
-- ADDITIVE ONLY. Two tables, two enums, one enum VALUE, four columns, five
-- foreign keys. Nothing is dropped and nothing is altered, so the expand/contract
-- window #378 paid for does not arise: the running build cannot notice any of it.
--
-- Generated by `prisma migrate diff --from-schema-datamodel --to-schema-datamodel`,
-- which opens NO database connection. Never `--from-migrations`, which demands a
-- shadow database and, handed a real URL, DROPS AND RECREATES it -- that is how
-- ep-icy-hat was lost on 2026-09-18.
--
-- The `ALTER TYPE ... ADD VALUE` is safe inside Prisma's transaction because
-- nothing in this migration USES the new value; 20260927180000 added
-- QUOTE_EXTRACT the same way.
--
-- Every ADD CONSTRAINT below is on ONE LINE deliberately. #224's hand-written
-- migration wrapped after the constraint name, `scratch-cleanup-order.test.ts`
-- skipped it, and a guard went green on 180 foreign keys when the answer was 181.
-- The pattern takes `\s+` now, but formatting here is not worth relying on.

-- CreateEnum
CREATE TYPE "BidAddendumItemDecisionKind" AS ENUM ('MINE', 'NOT_MINE');

-- CreateEnum
CREATE TYPE "BidAddendumReferenceKind" AS ENUM ('SPEC_SECTION', 'DRAWING', 'SCHEDULE', 'REQUIREMENT', 'BID_PROCESS', 'GENERAL');

-- AlterEnum
ALTER TYPE "AiFeature" ADD VALUE 'ADDENDUM_READ';

-- AlterTable
ALTER TABLE "CompanyAiSettings" ADD COLUMN     "addendumPagesPerMonth" INTEGER NOT NULL DEFAULT 600;

-- AlterTable
ALTER TABLE "AskAllowancePeriod" ADD COLUMN     "addendumPagesUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "failedAddendumPages" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "BidAddendum" ADD COLUMN     "fileName" TEXT,
ADD COLUMN     "fileUrl" TEXT;

-- CreateTable
CREATE TABLE "BidAddendumReading" (
    "id" TEXT NOT NULL,
    "bidAddendumId" TEXT NOT NULL,
    "bidInvitationId" TEXT NOT NULL,
    "items" JSONB NOT NULL,
    "readingReason" TEXT NOT NULL,
    "proposedIssueDateText" TEXT,
    "proposedBidDateText" TEXT,
    "pagesCharged" INTEGER NOT NULL,
    "model" TEXT NOT NULL,
    "promptVersion" TEXT NOT NULL,
    "startedByUserId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "BidAddendumReading_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BidAddendumItemDecision" (
    "id" TEXT NOT NULL,
    "bidAddendumId" TEXT NOT NULL,
    "normalisedReference" TEXT NOT NULL,
    "displayReference" TEXT NOT NULL,
    "decision" "BidAddendumItemDecisionKind" NOT NULL,
    "decidedByUserId" TEXT,
    "decidedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BidAddendumItemDecision_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "BidAddendumReading_bidAddendumId_createdAt_idx" ON "BidAddendumReading"("bidAddendumId", "createdAt");

-- CreateIndex
CREATE INDEX "BidAddendumReading_bidInvitationId_idx" ON "BidAddendumReading"("bidInvitationId");

-- CreateIndex
CREATE INDEX "BidAddendumItemDecision_bidAddendumId_idx" ON "BidAddendumItemDecision"("bidAddendumId");

-- CreateIndex
CREATE UNIQUE INDEX "BidAddendumItemDecision_bidAddendumId_normalisedReference_key" ON "BidAddendumItemDecision"("bidAddendumId", "normalisedReference");

-- AddForeignKey
ALTER TABLE "BidAddendumReading" ADD CONSTRAINT "BidAddendumReading_bidAddendumId_fkey" FOREIGN KEY ("bidAddendumId") REFERENCES "BidAddendum"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BidAddendumReading" ADD CONSTRAINT "BidAddendumReading_bidInvitationId_fkey" FOREIGN KEY ("bidInvitationId") REFERENCES "BidInvitation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BidAddendumReading" ADD CONSTRAINT "BidAddendumReading_startedByUserId_fkey" FOREIGN KEY ("startedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BidAddendumItemDecision" ADD CONSTRAINT "BidAddendumItemDecision_bidAddendumId_fkey" FOREIGN KEY ("bidAddendumId") REFERENCES "BidAddendum"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BidAddendumItemDecision" ADD CONSTRAINT "BidAddendumItemDecision_decidedByUserId_fkey" FOREIGN KEY ("decidedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

