import { test, expect } from "@playwright/test";
import { signInAs } from "../lib/signIn";
import { PERSONAS } from "../lib/personas";
import { HealthMonitor, expectHealthy } from "../lib/health";

/**
 * THE ONLY WAY OFF A PAGE ON A PHONE, and nothing in this suite had ever
 * pressed it.
 *
 * Below Tailwind's `md` the 240px rail is `display: none` (Sidebar.tsx's
 * spacer is `hidden … md:block`) and MobileNav.tsx's hamburger and drawer
 * are the app's navigation. MobileNav.tsx's own header calls that button
 * "the gateway to every field screen on a phone" — half a subcontractor's
 * people are in the field — and the machine had never clicked it, at any
 * width, which is how a shell with no navigation landmark at all shipped
 * for weeks without anybody noticing.
 *
 * Three things, in the order a thumb meets them:
 *
 *   1. The desktop rail's landmark is NOT there at 375px. Asserted rather
 *      than assumed, because everything below is only interesting if the
 *      rail is genuinely absent — if it were somehow visible on a phone,
 *      this spec would be proving the drawer while a 240px column ate two
 *      thirds of the screen.
 *   2. The hamburger is visible, and it OPENS something.
 *   3. What it opens is a navigation landmark NAMED "Main" (the fix that
 *      rides with this spec — that `<nav>` had no accessible name, so a
 *      signed-in phone page had no named navigation landmark anywhere),
 *      and it carries the link for the page you are standing on, marked
 *      `aria-current="page"`.
 *
 * Point 3's second half is deliberately not "a link called Punch lists":
 * `aria-current` is generated by the drawer from the CURRENT pathname, so
 * it cannot be true before the drawer renders — CLAUDE.md's rule that a
 * signal must be something that cannot already be on the page. A hardcoded
 * label would also break the moment Cyrus renames a nav entry, which
 * navItems.tsx's own comments say is his to do.
 *
 * EMPTY persona and a read-only page, like its neighbours in
 * specs/field-screens.mobile.spec.ts: nothing here writes a row.
 */
test("the phone shell's navigation opens, and it is a landmark with a name", async ({ page }) => {
  const monitor = new HealthMonitor(page);
  await signInAs(page, PERSONAS.empty.email);
  await page.goto("/punch-lists");

  // The drawer is closed, so the app has exactly one navigation landmark
  // question at this width and the answer is "not the rail".
  await expect(
    page.getByRole("navigation", { name: "Main" }),
    "at 375px the desktop rail must NOT be in the accessibility tree — it is display:none below md",
  ).toBeHidden();

  const open = page.getByRole("button", { name: "Open navigation" });
  await expect(open, "the hamburger is the whole of the navigation on a phone").toBeVisible();

  // The same check every other page in this suite gets, which at this width
  // is now a check on THIS button (lib/health.ts, expectShellNavigation).
  await expectHealthy(page, "/punch-lists at 375px", { monitor });

  await open.click();

  const drawer = page.getByRole("navigation", { name: "Main" });
  await expect(
    drawer,
    'the drawer must be a navigation landmark named "Main" — an unnamed one is announced as bare "navigation"',
  ).toBeVisible();

  // Where you are, drawn by the drawer from the current pathname.
  await expect(
    drawer.locator('[aria-current="page"]'),
    "the drawer must mark the page you are on — /punch-lists here",
  ).toBeVisible();
  await expect(drawer.locator('[aria-current="page"]')).toHaveAttribute("href", "/punch-lists");

  // Escape closes it, which is the only way back to the page one-handed
  // without hitting a link by accident. (MobileNav's keydown listener.)
  await page.keyboard.press("Escape");
  await expect(drawer).toBeHidden();
});
