-- Estimate templates: the shape of a job you bid over and over, saved once.
-- Two new tables.
--
-- PURELY ADDITIVE. Nothing dropped, no existing column altered, no existing
-- row touched.
--
-- THIS IS NOT A SECOND HOME FOR LINE-ITEM DATA, which ARCHITECTURE.md's one
-- non-negotiable rule forbids. It is company reference data that GENERATES
-- JobLineItem rows, the same job LineItemCatalogEntry and WallTypeComponent
-- already do. EstimateTemplateItem.catalogEntryId is SET NULL for the reason
-- WallTypeComponent gives: re-pricing the catalog must never reach back into
-- a line already sitting on somebody's estimate.
--
-- EstimateTemplateItem carries no companyId and is scoped through its
-- template, the same call WallTypeComponent makes. Neither table carries a
-- jobId, so neither needs cleanup-script registration.
--
-- Generated by schema-to-schema diff (--from-schema-datamodel /
-- --to-schema-datamodel), which opens no database connection. Never
-- --shadow-database-url.

-- CreateTable
CREATE TABLE "EstimateTemplate" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "tradeScope" "TradeScope",
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EstimateTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EstimateTemplateItem" (
    "id" TEXT NOT NULL,
    "templateId" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "unit" TEXT,
    "defaultQuantity" DECIMAL(12,2),
    "catalogEntryId" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EstimateTemplateItem_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "EstimateTemplate_companyId_idx" ON "EstimateTemplate"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "EstimateTemplate_companyId_name_key" ON "EstimateTemplate"("companyId", "name");

-- CreateIndex
CREATE INDEX "EstimateTemplateItem_templateId_idx" ON "EstimateTemplateItem"("templateId");

-- AddForeignKey
ALTER TABLE "EstimateTemplate" ADD CONSTRAINT "EstimateTemplate_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EstimateTemplateItem" ADD CONSTRAINT "EstimateTemplateItem_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "EstimateTemplate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EstimateTemplateItem" ADD CONSTRAINT "EstimateTemplateItem_catalogEntryId_fkey" FOREIGN KEY ("catalogEntryId") REFERENCES "LineItemCatalogEntry"("id") ON DELETE SET NULL ON UPDATE CASCADE;

