import { FORM_MEANINGS, FORM_NAMES, FINAL_WARNING, NEW_MEXICO, STATE_CONTENT, UNCONDITIONAL_WARNING } from "@/lib/content";
import type { SourceMeta } from "./build";
import { NORMALIZATION_LIST_VERSION, NORMALIZATION_RULES } from "./normalization";
import { QUESTIONS } from "./questions";
import { SLOTS } from "./slots";
import { STATES, type BuiltForm, type FormDefinition, type StateCode } from "./types";

/**
 * The attorney packet, as Markdown, GENERATED -- by generated.test.ts, into
 * docs/attorney-packet.md -- so its form text, its list of removals and its
 * review digests are the ones the code ships, and cannot be a stale copy.
 *
 * For every form it shows the published text (as extracted, before any
 * removal), every removal with the exact characters, and the text as the
 * tool prints it with the blanks empty. The raw captured page itself is in
 * statutes/raw/, byte for byte, with its SHA-256.
 */

export interface PacketInput {
  definitions: FormDefinition[];
  forms: BuiltForm[];
  paragraphs: Record<string, string[]>;
  meta: Record<string, SourceMeta>;
  digest: (state: StateCode) => string;
}

const fence = (text: string) => "```text\n" + text + "\n```";

export function buildPacket({ definitions, forms, paragraphs, meta, digest }: PacketInput): string {
  const out: string[] = [];
  out.push(
    "# Lien waiver tool — attorney packet",
    "",
    "<!-- GENERATED by lib/statutes/generated.test.ts. Do not edit by hand: run `pnpm --filter @prova/lien-waiver statutes:update`. -->",
    "",
    "This packet is everything a reviewer needs to approve, or correct, one state of the free lien waiver tool:",
    "the statutory text as published, every character the tool removes and why, the text exactly as printed,",
    "our own plain-English words about the state, and the questions we could not answer ourselves.",
    "",
    "**How a review is recorded.** Each state below ends with a *review digest*: a SHA-256 over that state's four",
    "printed forms, the normalization list version and our copy for the state. A review is recorded against that",
    "digest (`lib/statutes/review.ts`). If any of it changes afterwards, the digest changes, the review stops",
    "matching, and the state is hidden in production until it is reviewed again.",
    "",
    "Paragraph numbers are 0-based indexes into `statutes/text/<source>.txt` (line = index + 1).",
    "",
    `## The normalization list (version ${NORMALIZATION_LIST_VERSION})`,
    "",
    "These are the only differences allowed between a statute's published form and what the tool prints.",
    "",
  );
  NORMALIZATION_RULES.forEach((rule, i) => {
    out.push(`${i + 1}. **${rule.name}** (\`${rule.id}\`). ${rule.description}`, `   *Example:* ${rule.example}`);
  });
  out.push("", "## General questions", "");
  for (const q of QUESTIONS.GENERAL) out.push(`- **${q.id}.** ${q.question}`, `  *Today:* ${q.whatTheToolDoesNow}`);
  out.push(
    "",
    "## Our words, used for every state",
    "",
    "Form names and meanings shown when a form is chosen:",
    "",
  );
  for (const key of Object.keys(FORM_NAMES) as Array<keyof typeof FORM_NAMES>) {
    out.push(`- **${FORM_NAMES[key]}.** ${FORM_MEANINGS[key]}`);
  }
  out.push("", `Shown with every unconditional form: “${UNCONDITIONAL_WARNING}”`, "", `Shown with every final form: “${FINAL_WARNING}”`, "");
  out.push("Labels for the blanks (ours, beside the form, never on it):", "");
  for (const [id, spec] of Object.entries(SLOTS)) {
    out.push(`- \`${id}\`: ${spec.label}${spec.help ? ` — ${spec.help}` : ""}${spec.fillable ? "" : " (never filled)"}`);
  }

  for (const state of STATES) {
    const content = STATE_CONTENT[state];
    const stateDefs = definitions.filter((definition) => definition.state === state);
    const source = meta[stateDefs[0].sourceId];
    out.push(
      "",
      `## ${content.name} — ${content.statute}`,
      "",
      "| | |",
      "| --- | --- |",
      `| Source page | ${source.requestedUrl} |`,
      `| Statute | ${source.citation} |`,
      `| Retrieved | ${source.retrievedAt} |`,
      `| Captured by | ${source.capturedVia === "headless-render" ? "rendering the page in a headless browser (the site does not serve the text to a plain request)" : "a direct download by the Capture statutes workflow"} |`,
      `| Raw capture | \`statutes/raw/${source.id}.html\`, SHA-256 \`${source.sha256}\` |`,
      `| Brand header/footer | ${content.brandFrame ? "on" : "off"} |`,
      "",
      "Our words about this state, as shown on its page:",
      "",
      `- *How closely the form must be followed:* ${content.formRequirement}`,
      `- *Who signs:* ${content.signer}`,
      `- *Notary:* ${content.notarization}`,
      ...content.notes.map((note) => `- ${note}`),
      "",
      "Questions:",
      "",
    );
    for (const q of QUESTIONS[state]) out.push(`- **${q.id}.** ${q.question}`, `  *Today:* ${q.whatTheToolDoesNow}`);

    for (const definition of stateDefs) {
      const form = forms.find((candidate) => candidate.state === state && candidate.form === definition.form)!;
      const [first, last] = definition.span;
      const published = paragraphs[definition.sourceId].slice(first, last + 1).map((text, i) => {
        const index = first + i;
        const drafting = definition.drafting.find((entry) => entry.index === index);
        return `[${index}]${drafting ? " (DRAFTING — NOT PRINTED)" : ""} ${text}`;
      });
      out.push(
        "",
        `### ${FORM_NAMES[definition.form]} — ${definition.citation}`,
        "",
        `Printed text SHA-256: \`${form.textSha256}\``,
        "",
        form.noticeRule
          ? `Notice rule: ${form.noticeRule.authority} Placement: **${form.noticeRule.placement === "top" ? "top of the document" : "where the statute sets it out"}**.`
          : "No separate notice rule.",
        "",
        `**As published** (paragraphs ${first}–${last} of \`statutes/text/${definition.sourceId}.txt\`):`,
        "",
        fence(published.join("\n")),
        "",
        "**Removed:**",
        "",
      );
      const removals = [
        ...definition.drafting.map((entry) => `- Paragraph ${entry.index}, whole (rule \`drafting-instruction\`): ${entry.why}`),
        ...definition.edits.map(
          (edit) => `- Paragraph ${edit.index}, ${edit.at === "start" ? "first" : "last"} characters \`${edit.text}\` (rule \`${edit.rule}\`)`,
        ),
      ];
      out.push(...(removals.length ? removals : ["- Nothing."]));
      out.push(
        "",
        "**As printed** (blanks shown as published; the tool writes values in their place):",
        "",
        fence(form.paragraphs.map((paragraph) => paragraph.text).join("\n")),
      );
    }
    out.push("", `**Review digest for ${content.name}:** \`${digest(state)}\``);
  }

  out.push(
    "",
    "## New Mexico",
    "",
    NEW_MEXICO.finding,
    "",
    NEW_MEXICO.consequence,
    "",
    `Source examined: ${meta["nm-48-2"]?.requestedUrl ?? "(not captured)"} (the official NMSA 1978 Chapter 48 document, retrieved ${meta["nm-48-2"]?.retrievedAt ?? "?"}, SHA-256 \`${meta["nm-48-2"]?.sha256 ?? "?"}\`).`,
    "",
  );
  for (const q of QUESTIONS.NM) out.push(`- **${q.id}.** ${q.question}`, `  *Today:* ${q.whatTheToolDoesNow}`);
  out.push(
    "",
    "## Privacy notice and terms",
    "",
    "See question G-7. The pages are `app/privacy/page.tsx` and `app/terms/page.tsx`, rendered at `/privacy` and `/terms` on the preview.",
    "",
  );
  return out.join("\n");
}
