-- An amendment record for logged time entries (issue #63).
--
-- Purely additive: one new table, its index, and one foreign key. Nothing
-- existing is dropped, renamed, or altered, so this is safe against the
-- real data in the sense CLAUDE.md means — a drop is the irreversible one.
--
-- The SQL below was generated by `prisma migrate diff` from the schema
-- before and after the change (schema-to-schema, no database involved), not
-- typed by hand.
--
-- ON DELETE CASCADE is deliberate. Deleting a time entry is still offered
-- and is now two-step; when a row does go, its corrections go with it,
-- because a correction to a row that no longer exists is an orphan, not
-- evidence.

-- CreateTable
CREATE TABLE "TimeEntryCorrection" (
    "id" TEXT NOT NULL,
    "timeEntryId" TEXT NOT NULL,
    "correctedByUserId" TEXT NOT NULL,
    "correctedByName" TEXT NOT NULL,
    "correctedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reason" TEXT NOT NULL,
    "previousHours" DECIMAL(5,2) NOT NULL,
    "previousPayType" "TimeEntryPayType" NOT NULL,
    "previousCraftLabel" TEXT,
    "previousLineItemLabel" TEXT,
    "previousPerDiemAmount" DECIMAL(10,2),
    "previousTravelPayAmount" DECIMAL(10,2),
    "previousNote" TEXT,

    CONSTRAINT "TimeEntryCorrection_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TimeEntryCorrection_timeEntryId_idx" ON "TimeEntryCorrection"("timeEntryId");

-- AddForeignKey
ALTER TABLE "TimeEntryCorrection" ADD CONSTRAINT "TimeEntryCorrection_timeEntryId_fkey" FOREIGN KEY ("timeEntryId") REFERENCES "TimeEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
