-- The plan-ingestion job runner: one job per plan set, one task per page per
-- stage, and a claim column that makes a 300-page run resumable.
--
-- FULLY ADDITIVE. One enum, two tables, six indexes plus one unique index,
-- and four foreign keys. Counted from this file rather than remembered — the
-- first version of this line said seven indexes, which was true before the
-- backoff column earned its own.
-- Nothing is dropped and no existing row changes meaning, so #378's
-- expand/contract outage window does not arise: the running build selects none
-- of it.
--
-- GENERATED BY A SCHEMA-TO-SCHEMA DIFF — `--from-schema-datamodel` against the
-- schema as it stands on HEAD, `--to-schema-datamodel` against this working
-- tree. NO DATABASE WAS CONNECTED TO, and that is the rule rather than a
-- preference: `--shadow-database-url` DROPS AND RECREATES whatever it is
-- pointed at, and on 2026-09-18 it was pointed at ep-icy-hat and took every
-- company, job and test record with it.
--
-- TWO THINGS A REVIEWER SHOULD QUESTION, ANSWERED HERE:
--
-- 1. `PlanIngestJob.companyId` is a RESTRICT child of `Company`, like
--    `CompanyAiSettings` and `AskUsage` before it. That blocks deleting a
--    COMPANY, which nothing in this app does — the scratch cleanup deletes
--    under `Job` and `Contact`. It does NOT block deleting a job.
--
-- 2. Neither model needs registering in `HANDLED_MODELS` or the two cleanup
--    `del()` orders, and the reason is `TakeoffPlan`'s own design: it is the
--    single `jobId` in takeoff.prisma on purpose, and everything beneath it
--    CASCADEs, so one `takeoffPlan.deleteMany({ jobId })` reaches all of this.
--    `PlanIngestJob.planId` CASCADEs from the plan and `PlanIngestTask.jobId`
--    CASCADEs from the job.
--
--    That claim is CHECKED rather than asserted — `scratch-cleanup-order.test.ts`
--    derives the blocking foreign keys from this SQL and counts them
--    independently of the pattern that found them. #224 shipped a counter that
--    issued numbers perfectly and broke both cleanup scripts, with the guard
--    green the whole way, because its per-job counter was a RESTRICT child that
--    deleting the job's invoices never reached.
--
-- `PlanIngestTask.attempts` increments ON CLAIM, not on failure, and the
-- column comment in plan-ingest.prisma explains why: an attempt that dies
-- before it can write anything is exactly the failure a poison page produces,
-- and counting failures would retry it forever.
-- CreateEnum
CREATE TYPE "PlanIngestStage" AS ENUM ('PAGE_INVENTORY', 'CLASSIFY', 'TITLE_BLOCK', 'SHEET_INDEX');

-- CreateTable
CREATE TABLE "PlanIngestJob" (
    "id" TEXT NOT NULL,
    "planId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "stage" "PlanIngestStage" NOT NULL,
    "pageCount" INTEGER NOT NULL,
    "startedAt" TIMESTAMP(3),
    "finishedAt" TIMESTAMP(3),
    "startedByUserId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PlanIngestJob_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PlanIngestTask" (
    "id" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "pageNumber" INTEGER NOT NULL,
    "stage" "PlanIngestStage" NOT NULL,
    "claimedAt" TIMESTAMP(3),
    "claimExpiresAt" TIMESTAMP(3),
    "finishedAt" TIMESTAMP(3),
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "error" TEXT,
    "nextAttemptAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PlanIngestTask_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "PlanIngestJob_planId_stage_idx" ON "PlanIngestJob"("planId", "stage");

-- CreateIndex
CREATE INDEX "PlanIngestJob_companyId_createdAt_idx" ON "PlanIngestJob"("companyId", "createdAt");

-- CreateIndex
CREATE INDEX "PlanIngestJob_startedByUserId_idx" ON "PlanIngestJob"("startedByUserId");

-- CreateIndex
CREATE INDEX "PlanIngestTask_jobId_finishedAt_claimedAt_idx" ON "PlanIngestTask"("jobId", "finishedAt", "claimedAt");

-- CreateIndex
CREATE INDEX "PlanIngestTask_nextAttemptAt_idx" ON "PlanIngestTask"("nextAttemptAt");

-- CreateIndex
CREATE INDEX "PlanIngestTask_claimExpiresAt_idx" ON "PlanIngestTask"("claimExpiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "PlanIngestTask_jobId_pageNumber_stage_key" ON "PlanIngestTask"("jobId", "pageNumber", "stage");

-- AddForeignKey
ALTER TABLE "PlanIngestJob" ADD CONSTRAINT "PlanIngestJob_planId_fkey" FOREIGN KEY ("planId") REFERENCES "TakeoffPlan"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlanIngestJob" ADD CONSTRAINT "PlanIngestJob_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlanIngestJob" ADD CONSTRAINT "PlanIngestJob_startedByUserId_fkey" FOREIGN KEY ("startedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlanIngestTask" ADD CONSTRAINT "PlanIngestTask_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "PlanIngestJob"("id") ON DELETE CASCADE ON UPDATE CASCADE;

