-- Which issue of the drawings a takeoff was measured off, so the app can say
-- when quantities came from superseded paper.
--
-- PURELY ADDITIVE: two nullable columns. Nothing dropped, nothing altered, no
-- existing row touched. Every existing plan reads as UNKNOWABLE rather than
-- current, which is the honest default — a plan whose issue date nobody
-- recorded cannot be shown to be superseded, and cannot be shown to be
-- current either.
--
-- TEXT AND A DATE, NOT A FOREIGN KEY to DrawingRevision. takeoff.prisma's own
-- header says TakeoffPlan "must not become" DrawingSet/DrawingRevision: those
-- record the job's paper trail, while this is a sheet somebody was emailed
-- with an invitation to bid — and at bid time the job usually has no drawing
-- set at all. Currency is worked out by comparing dates and labels, never by
-- following a relation.
--
-- Generated by schema-to-schema diff. Never --shadow-database-url.

-- AlterTable
ALTER TABLE "TakeoffPlan" ADD COLUMN     "revisionLabel" TEXT,
ADD COLUMN     "sheetIssuedOn" TIMESTAMP(3);

